### ISSUE TITLE
Focus to another monitor which contains same application, it will focus the application on current monitor but not focus next/prev monitor.

### ISSUE THREAD

**Issue by z1645444** [nikitabobko/AeroSpace#658] opened 2024-11-04 04:05 UTC
From monitor A launch a browser(or other applications), and create a new window, move it to next monitor - monitor B. So far everything works perfect.

Now launch any other app on monitor A, focus that app window. Then try to focus monitor B. We focus brower. Try to focus monitor B again. We focus monitor B.

You have to focus on the cloned window at first, then could make a move.

I also tried run command on termianl to make a focus move. Same.

It's fine if I just use one monitor. I can focus other desktop as usual even if I open browsers on every desktop.

**Comment by nikitabobko** [comment] 2024-11-04 09:18
Duplicate of #101

**Closed by nikitabobko** 2024-11-04 09:18 UTC
Labels: bug
