### ISSUE TITLE
Focus the window under cursor

### ISSUE THREAD

**Issue by sameer1612** [nikitabobko/AeroSpace#379] opened 2024-08-11 19:14 UTC
I come from Yabai where I have an option for "focus follows mouse". 

Is there something equivalent in Aerospace? Asking just for the sake of muscle reflex from my long term usage in Yabai.

Appreciate any help or link to the right config. Thanks!

**Comment by nabahool** [comment] 2024-08-11 20:15
duplicate of #12

**Closed** 2024-08-11 20:22 UTC
