### ISSUE TITLE
`move-node-to-workspace` not triggering `exec-on-workspace-change` in `[[on-window-detected]]` clause

### ISSUE THREAD

**Issue by typkrft** [nikitabobko/AeroSpace#402] opened 2024-08-13 17:15 UTC
An established event for `sketchybar` appears not trigger when window is automatically moved to a workspace. 

Relevant toml
```toml
# Sketchybar
exec-on-workspace-change = [
    '/bin/bash', 
    '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

[[on-window-detected]]
if.app-id = 'com.apple.Music'
run = ['move-node-to-workspace 3']
```

Relevant sketchybarrc
```bash
sketchybar --add event aerospace_workspace_change
for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space.$sid left \
        --subscribe space.$sid aerospace_workspace_change space_windows_change space_change \
        --set space.$sid \
        background.color=0xffffffff  \
        background.corner_radius=5 \
        background.height=20 \
        background.drawing=off \
        icon.drawing=off \
        label="$sid" \
        label.padding_right=6 \
        click_script="aerospace workspace $sid" \
        script="$PLUGIN_DIR/aerospace.sh $sid"
done
```

Aerospace Script
```bash
#!/usr/bin/env bash

# Set Background
if [[ -z "$FOCUSED_WORKSPACE" ]]; then
    focused_space=$(aerospace list-workspaces --focused)
    sketchybar --set space.$focused_space background.drawing=on label.color=0xff000000 label="$focused_space [$(aerospace list-windows --workspace focused | wc -l | grep -Eo '\d')]"
elif [[ "$1" = "$FOCUSED_WORKSPACE" ]]; then
    sketchybar --set $NAME background.drawing=on label.color=0xff000000 label="$1 [$(aerospace list-windows --workspace focused | wc -l | grep -Eo '\d')]"
else
    sketchybar --set $NAME background.drawing=off label.color=0x44ffffff label="$(echo $NAME | grep -Eo '[0-9]{1,4}')"
fi
```

**Comment by bassamsdata** [comment] 2024-08-13 19:19
I have a similar issue where it doesn't seem to trigger the event, or the environment variable is empty. When I run this in the terminal:

`echo $AEROSPACE_FOCUSED_WORKSPACE`

It outputs nothing, but it should output the focused workspace, right?

OS: MacOS
version:
aerospace CLI client version: 0.14.1-Beta 5861e85b65cb7dc914a0a68027c56e2bc90510fd
AeroSpace.app server version: 0.14.1-Beta 5861e85b65cb7dc914a0a68027c56e2bc90510fd

**Comment by nikitabobko** [comment] 2024-08-13 20:15
`exec-on-workspace-change` is invoked when focused workspace changes
`move-node-to-workspace` doesn't change focused workspace

**Comment by typkrft** [comment] 2024-08-14 00:26
Is there an event that would trigger anytime a workspace is manipulated? If not I would be nice. Also I apologize for minimal information. I update my space indicators in sketchybar dynamically. I have another script that fires which removes old workspaces with no windows in them and adds the number of windows in a given workspace to the focused workspace. So when I use a rule to automatically move a window, sketchybar doesn't indicate that the space now has a window in it. This is really a minor annoyance, but it would be nice. 


Script in question for posterity.  It's a hack job. 
```bash
#!/usr/bin/env zsh
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

if [[ -z "$1" ]]; then 
    1=$(aerospace list-workspaces --focused)
fi

# If space doesn't exist
if ! sketchybar --query space."$1" &> /dev/null; then 
    
    # Get Position
    position=""
    for i in {1..9}; do 
        if sketchybar --query space."$i" &> /dev/null; then 
            position="$i"
            continue
        fi
        break
    done


    # Create Space
    sketchybar --add item space.$1 left             \
    --subscribe space.$1 aerospace_workspace_change \
    --set space.$1                                  \
    background.color=0xff{{ .dracula.hex.purple }}  \
    background.corner_radius=5                      \
    background.height=20                            \
    background.drawing=off                          \
    icon.drawing=off                                \
    label=$1                                        \
    label.padding_right=6                           \
    click_script="aerospace workspace $1"           \
    script="$PLUGIN_DIR/aerospace.sh $1"            \
    --move space.$1 before chevron                  \
    --move space.$1 after space.$position

    bash -c "$PLUGIN_DIR/aerospace.sh $1"
fi

# Remove Empty Spaces
rm_spaces=()
for i in {1..9}; do
    matched=0
    for j in $(aerospace list-workspaces --all); do 
        if [[ "$j" -eq "$i" ]]; then 
            matched=1
            break
        fi
    done

    if [[ "$matched" -eq 1 ]]; then 
        continue
    fi
    rm_spaces+=("$i")
done

for space in $rm_spaces; do
    sketchybar --remove space.$space
done
```

**Comment by nikitabobko** [comment] 2024-08-14 09:26
Duplicate of #316

**Closed by nikitabobko** 2024-08-14 09:26 UTC
