### ISSUE TITLE
Feature request: visualization of current tree layout

### ISSUE THREAD

**Issue by eugeneotto** [nikitabobko/AeroSpace#55] opened 2023-12-14 19:31 UTC
I'm coming from the Rectangle app and have found it hard to adapt my workflow to a tiling window system. I think the main challenge is that it's often difficult for me to map what I see on the screen to what Aerospace's internal tree representation is, which I believe is a prerequisite to being able to manipulate the windows efficiently (please let me know if I'm mistaken!)

If Aerospace had a way to visually communicate the internal tree structure at any given time, then it might be easier for people to get the hang of things. I'm not sure how to do this in realtime without affecting the tree structure (kind of a Schrödinger's cat situation 😅). A half-step might be a command + hot key that takes a screen grab and overlays a representation of the tree structure so you can at least review after the fact.

I know this is a little out there :) Feel free to close, and maybe I will take a crack at this when I find some time.

**Comment by DonaldoSoWell** [comment] 2023-12-16 10:49
Maybe #16 will provide a first way to do it

**Comment by nikitabobko** [comment] 2024-06-08 12:41
I mark this issue as duplicate of #16 & #236

`tree` command run in "interactive" mode should cover the use case

**Closed by nikitabobko** 2024-06-08 12:41 UTC
