### ISSUE TITLE
Config on number of monitors or machine

### ISSUE THREAD

**Issue by alper** [nikitabobko/AeroSpace#823] opened 2024-12-06 09:55 UTC
Hi! Really love the work on Aerospace. I thought I'd go into automating my assignment a bunch more but ran into this:

1. I'd need to make the force assignment different if I have a two monitor setup or I'm working only on my laptop.
2. Less important: I'd probably also want to setup things differently on different machines if possible.

I'm not sure what would be an easy way to get the first one done.

**Comment by nikitabobko** [comment] 2024-12-06 10:15
Duplicate of #115

**Closed by nikitabobko** 2024-12-06 10:15 UTC
Labels: feature-proposal

**Comment by alper** [comment] 2024-12-06 11:07
OK. I see how that would cover hostname based config, but how would it work for the same machine where I plug in a monitor?

**Comment by nikitabobko** [comment] 2024-12-06 11:17
> but how would it work for the same machine where I plug in a monitor?

Please read the docs on the force assignment, it's already possible

**Comment by alper** [comment] 2024-12-06 11:27
I read the entire thing again and I literally don't see how.

I'd like:
* Windows to be split between workspace 1 (laptop) and workspace 2 (secondary screen)
* Windows to all be on workspace 1 if secondary screen is not there

Right now if I disconnect an external screen I have workspace 1 and workspace 2 both on my laptop with the windows split between them.

**Comment by gplusplus314** [comment] 2025-01-06 20:49
I don't see how this is a duplicate of #115 , either. I, too, cannot find relevant information in the docs on how to accomplish monitor assignment *via configuration*. I do see the `[move-workspace-to-monitor](https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor)` command, but that does not accomplish what we're looking for.

The use case is to effectively dedicate certain workspaces to certain monitors. The concept of a "next" or "previous" monitor won't work here; we'd want to assign based on a monitor identifier so that it's deterministic. A concrete example, for me at least, is to put my workspaces with chat and video conference apps (Zoom, Slack, etc) that default to a secondary monitor I have off to the side when I'm docked on my desk. When not docked and I'm portable, I'd want that workspace to just join the others on the built-in MacBook monitor.

This automatic arrangement when plugging back in to the dock and getting the second monitor is what we're looking for. If this is already possible, then I think there might be some missing documentation. @nikitabobko - could you please help us understand what we need to do to make this possible?

**Comment by nikitabobko** [comment] 2025-01-06 21:52
https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors

> You can specify multiple patterns. The first matching pattern will be used
