### ISSUE TITLE
Assign an app to more than one workspace

### ISSUE THREAD

**Issue by martinengelke** [nikitabobko/AeroSpace#588] opened 2024-10-14 02:49 UTC
**Assign Apps to more than one workspace** 

Maybe it's similar to the sticky note feature but I have an application called SideNotes which is floating from the side of my screen by invoking it. Unfortunately it just does it for one of my workspaces. 
I guess because those window is not really hidden or minimized, it just moves out of focus? I can move it via move-node.

I could imagine:
- 'move-node-to-frontmost-workspace' by detecting
- a 'follow_workspace' variable 
- or assign to 'workspace 0' to match all workspaces by detecting (similar approach apple does by assigning an App to several Desktops)

**I tried things like:**

[[on-window-detected]]
if.window-title-regex-substring = 'SideNotes'
check-further-callbacks = true
if.workspace = '1'
run = ['move-node-to-workspace 1']
if.workspace = '2'
run = ['move-node-to-workspace 2']
if.workspace = '3'
run = ['move-node-to-workspace 3']
if.workspace = '4'
run = ['move-node-to-workspace 4']

which are not working and may a bit hacky anyway. 

## Checklist

- [x ] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
  - assign to more than one workspace
  - app for multiple workspaces
  - ...
- [x ] I've read the guide https://nikitabobko.github.io/AeroSpace/guide
- [x ] I've searched in the documentation (https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands). My search queries were:
  - assign to more than one workspace
  - app for multiple workspaces
  - ...

```
AeroSpace v0.15.2-Beta b6cf82771f245ab7349a93baf8709e171537ff58
```

**Comment by nikitabobko** [comment] 2024-10-27 13:56
Duplicate of #378 #2

**Closed by nikitabobko** 2024-10-27 13:56 UTC
