### ISSUE TITLE
Overcounting alacritty tabs as windows

### ISSUE THREAD

**Issue by enigma** [nikitabobko/AeroSpace#474] opened 2024-08-30 09:35 UTC
Step to reproduce:

1. Open alacritty
2. press cmd+T to open a new tab

Expected behavior:
The alacritty window continues to occupy the full screen and you get a new tab in that single window

Actual behavior:
The alacritty window starts taking half the screen (as if I created a new alacritty window), the other half stays empty.

```bash 
$ aerospace list-windows --workspace focused
44410 | Alacritty | aerospace list-windows --workspace focused
43962 | Alacritty | ndr@nMBPwork:/tmp/alacritty1
```

See video:

https://github.com/user-attachments/assets/8aa95bb2-d2cb-488e-8db6-3c1cfe525fc8

I've added `aerospace debug-windows` from within the tab at the bottom.

## Checklist

- [x] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
  - alacritty
  - tabs
- [x] I've read the documentation https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands
- [x] I've searched in the documentation. My search queries were:
  - alacritty
  - tabs

```bash
$ aerospace --version
aerospace CLI client version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
AeroSpace.app server version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
```

### `aerospace debug-windows`

```
org.alacritty.window.44194 windowId: 44194
org.alacritty.window.44194 workspace: A
org.alacritty.window.44194 treeNodeParent: AppBundle.TilingContainer
org.alacritty.window.44194 recognizedAsDialog: false
org.alacritty.window.44194 AXTitle: Optional(aerospace debug-windows)
org.alacritty.window.44194 AXRole: Optional(AXWindow)
org.alacritty.window.44194 AXSubrole: Optional(AXStandardWindow)
org.alacritty.window.44194 AXFocused: Optional(1)
org.alacritty.window.44194 AXFullScreen: Optional(0)
org.alacritty.window.44194 AXFrame: Optional(<AXValue 0x6000006fb280> {value = x:-756.000000 y:456.000000 w:756.000000 h:943.000000 type = kAXValueCGRectType})
org.alacritty.window.44194 AXPosition: Optional(<AXValue 0x600001d54b10> {value = x:-756.000000 y:456.000000 type = kAXValueCGPointType})
org.alacritty.window.44194 AXGrowArea: nil
org.alacritty.window.44194 AXMinimizeButton: AXUIElement {
org.alacritty.window.44194      AXRole: Optional(AXButton)
org.alacritty.window.44194      AXTitle: nil
org.alacritty.window.44194      AXSubrole: Optional(AXMinimizeButton)
org.alacritty.window.44194      AXEnabled: Optional(1)
org.alacritty.window.44194      AXParent: AXUIElement(windowId=44194, title="aerospace debug-windows", role="AXWindow", subrole="AXStandardWindow")
org.alacritty.window.44194      AXTopLevelUIElement: AXUIElement(windowId=44194, title="aerospace debug-windows", role="AXWindow", subrole="AXStandardWindow")
org.alacritty.window.44194      AXWindow: AXUIElement(windowId=44194, title="aerospace debug-windows", role="AXWindow", subrole="AXStandardWindow")
org.alacritty.window.44194      Ignored: AXFrame, AXSize, AXFocused, AXHelp, AXPosition, AXRoleDescription
org.alacritty.window.44194 }
org.alacritty.window.44194 AXDocument: nil
org.alacritty.window.44194 AXSections: [
org.alacritty.window.44194         Optional({
org.alacritty.window.44194             SectionDescription = Content;
org.alacritty.window.44194             SectionObject = "<AXUIElement 0x600001d55290> {pid=6511}";
org.alacritty.window.44194             SectionUniqueID = AXContent;
org.alacritty.window.44194         })
org.alacritty.window.44194 ]
org.alacritty.window.44194 AXCloseButton: AXUIElement {
org.alacritty.window.44194      AXRole: Optional(AXButton)
org.alacritty.window.44194      AXTitle: nil
org.alacritty.window.44194      AXSubrole: Optional(AXCloseButton)
org.alacritty.window.44194      AXEnabled: Optional(1)
org.alacritty.window.44194      AXParent: AXUIElement(windowId=44194, title="aerospace debug-windows", role="AXWindow", subrole="AXStandardWindow")
org.alacritty.window.44194      AXTopLevelUIElement: AXUIElement(windowId=44194, title="aerospace debug-windows", role="AXWindow", subrole="AXStandardWindow")
org.alacritty.window.44194      AXWindow: AXUIElement(windowId=44194, title="aerospace debug-windows", role="AXWindow", subrole="AXStandardWindow")
org.alacritty.window.44194      Ignored: AXFrame, AXSize, AXFocused, AXHelp, AXPosition, AXRoleDescription, AXEdited
org.alacritty.window.44194 }
org.alacritty.window.44194 AXMain: Optional(1)
org.alacritty.window.44194 AXActivationPoint: Optional(<AXValue 0x600001d54b10> {value = x:-686.000000 y:470.000000 type = kAXValueCGPointType})
org.alacritty.window.44194 AXFullScreenButton: AXUIElement {
org.alacritty.window.44194      AXRole: Optional(AXButton)
org.alacritty.window.44194      AXTitle: nil
org.alacritty.window.44194      AXSubrole: Optional(AXFullScreenButton)
org.alacritty.window.44194      AXEnabled: Optional(1)
org.alacritty.window.44194      AXParent: AXUIElement(windowId=44194, title="aerospace debug-windows", role="AXWindow", subrole="AXStandardWindow")
org.alacritty.window.44194      AXTopLevelUIElement: AXUIElement(windowId=44194, title="aerospace debug-windows", role="AXWindow", subrole="AXStandardWindow")
org.alacritty.window.44194      AXWindow: AXUIElement(windowId=44194, title="aerospace debug-windows", role="AXWindow", subrole="AXStandardWindow")
org.alacritty.window.44194      Ignored: AXFrame, AXSize, AXFocused, AXChildren, AXHelp, AXPosition, AXRoleDescription
org.alacritty.window.44194 }
org.alacritty.window.44194 AXProxy: nil
org.alacritty.window.44194 AXDefaultButton: nil
org.alacritty.window.44194 AXMinimized: Optional(0)
org.alacritty.window.44194 AXParent: Optional(<AXUIElement Application 0x600001d54b10> {pid=6511})
org.alacritty.window.44194 AXTitleUIElement: AXUIElement(windowId=44194, title=nil, role="AXStaticText", subrole=nil)
org.alacritty.window.44194 AXCancelButton: nil
org.alacritty.window.44194 AXModal: Optional(0)
org.alacritty.window.44194 AXZoomButton: AXUIElement {
org.alacritty.window.44194      AXRole: Optional(AXButton)
org.alacritty.window.44194      AXTitle: nil
org.alacritty.window.44194      AXSubrole: Optional(AXFullScreenButton)
org.alacritty.window.44194      AXEnabled: Optional(1)
org.alacritty.window.44194      AXParent: AXUIElement(windowId=44194, title="aerospace debug-windows", role="AXWindow", subrole="AXStandardWindow")
org.alacritty.window.44194      AXTopLevelUIElement: AXUIElement(windowId=44194, title="aerospace debug-windows", role="AXWindow", subrole="AXStandardWindow")
org.alacritty.window.44194      AXWindow: AXUIElement(windowId=44194, title="aerospace debug-windows", role="AXWindow", subrole="AXStandardWindow")
org.alacritty.window.44194      Ignored: AXFrame, AXSize, AXFocused, AXChildren, AXHelp, AXPosition, AXRoleDescription
org.alacritty.window.44194 }
org.alacritty.window.44194 AXSize: Optional(<AXValue 0x600001d54b10> {value = w:756.000000 h:943.000000 type = kAXValueCGSizeType})
org.alacritty.window.44194 AXToolbarButton: nil
org.alacritty.window.44194 Ignored: AXChildrenInNavigationOrder, AXChildren, AXRoleDescription
org.alacritty              AXRole: Optional(AXApplication)
org.alacritty              AXTitle: Optional(Alacritty)
org.alacritty              AXFunctionRowTopLevelElements: [
org.alacritty              ]
org.alacritty              AXFrame: nil
org.alacritty              AXFocusedUIElement: AXUIElement(windowId=44194, title="aerospace debug-windows", role="AXWindow", subrole="AXStandardWindow")
org.alacritty              AXFrontmost: Optional(1)
org.alacritty              AXExtrasMenuBar: nil
org.alacritty              AXMainWindow: AXUIElement(windowId=44194, title="aerospace debug-windows", role="AXWindow", subrole="AXStandardWindow")
org.alacritty              AXFocusedWindow: AXUIElement(windowId=44194, title="aerospace debug-windows", role="AXWindow", subrole="AXStandardWindow")
org.alacritty              AXMenuBar: Optional(<AXUIElement 0x600001d54270> {pid=6511})
org.alacritty              AXWindows: [
org.alacritty                  AXUIElement(windowId=44194, title="aerospace debug-windows", role="AXWindow", subrole="AXStandardWindow"),
org.alacritty                  AXUIElement(windowId=25161, title="ndr@nMBPwork:~/coding/monorepo/src/titaness", role="AXWindow", subrole="AXStandardWindow"),
org.alacritty                  AXUIElement(windowId=1882, title="docker compose up --build", role="AXWindow", subrole="AXStandardWindow")
org.alacritty              ]
org.alacritty              AXSize: nil
org.alacritty              AXPosition: nil
org.alacritty              Ignored: AXChildren, AXChildrenInNavigationOrder, AXEnhancedUserInterface, AXPreferredLanguage, AXRoleDescription, AXHidden

!!! DISCLAIMER !!!
!!! 'debug-windows' command is not stable API. Please don't rely on the command existence and output format !!!
!!! The only intended use case is to report bugs about incorrect windows handling !!!
```

**Comment by nikitabobko** [comment] 2024-08-30 11:58
Duplicate of #68

**Closed by nikitabobko** 2024-08-30 11:58 UTC
