### ISSUE TITLE
Way to configure font used for the tray "icon"

### ISSUE THREAD

**Issue by graywolf** [nikitabobko/AeroSpace#360] opened 2024-08-06 10:31 UTC
Hi,

I am unsure what the correct Mac terminology is, but when AeroSpace is running, there is tiny tray "icon" with the current workspace.  I would appreciate a way to configure font used to render the workspace.

Why:  I often switch between `1` and `2` workspaces and `1` is narrowed than `2`.  So rest of the icons in the tray menu jump shift slightly left or right.  It is not a deal breaker, but it is noticeable and somewhat irritating.  Setting the font to some monospaced font would solve the issue.

**Comment by bcremer** [comment] 2024-08-06 10:54
Duplicate of https://github.com/nikitabobko/AeroSpace/issues/56

**Closed** 2024-08-06 13:54 UTC
