### ISSUE TITLE
Highlight focused window

### ISSUE THREAD

**Issue by Kantis** [nikitabobko/AeroSpace#271] opened 2024-06-12 08:01 UTC
In my opinion, it's very hard to identify the focused on a large screen or multi-monitor setup with a bunch of tiled windows. Somehow aiding in this process would be very practical _imo_. Identifying the currently focused window is necessary to perform: `move`, `join-with`, `layout`, `focus`, `resize`.

I know this goes against the current value-statement of the project, but I'd like to open the discussion anyway because IMO this is not merely a question of fancy appearance.
> Provide practical features. Fancy appearance features are not practical (e.g. window borders, transparency, etc)

---
### Workaround
I've currently added Hammerspoon which provides this functionality, but since it does not integrate with AeroSpace, there's noticeable delays for the overlay to refresh when changing focused window.

**Comment by nikitabobko** [comment] 2024-06-12 08:35
Duplicate of #85

**Closed by nikitabobko** 2024-06-12 08:35 UTC
