### ISSUE TITLE
[Feature Request] Implement mouse-follows-focus

### ISSUE THREAD

**Issue by sigfriedCub1990** [nikitabobko/AeroSpace#62] opened 2023-12-18 20:30 UTC
First of all, thanks for making Aerospace!! 
I've been using it as my daily driver for about a month now and I'm very pleased with it.
However, if possible, I would like to have something like `mouse-follows-focus` implemented. This is something I first saw while using `yabai` a couple of years ago and I also saw it while using `amethyst`.

My use case is quite simple, I mainly do web development using a 32" monitor and, while making prototypes or doing manual testing, I need to use the mouse to test the interactions. It would be nice if the mouse is already in the center of the window so I don't need to move it from left/right.

**Comment by nikitabobko** [comment] 2023-12-18 23:02
Duplicate of #12

**Closed by nikitabobko** 2023-12-18 23:02 UTC
