### ISSUE TITLE
save/restore layout

### ISSUE THREAD

**Issue by januz** [nikitabobko/AeroSpace#70] opened 2023-12-26 01:16 UTC
Thanks for developing this application! I'm exploring tiling window managers for the first time and was assuming that `yabai` was the only option but was pointed towards `AeroSpace` as an alternative and like it a lot!

I was wondering whether you're planning on supporting saving and restoring window layouts. Especially for my secondary monitor which I use for one or two of my workspaces with always the same set of applications arranged in the same layout, it would be fantastic to be able to set them up with one command on startup (and/or restore them later if they got mangled). i3 seems to support this: https://i3wm.org/docs/layout-saving.html

Thanks so much!

**Comment by nikitabobko** [comment] 2023-12-26 01:52
Duplicate of #57

**Closed by nikitabobko** 2023-12-26 01:52 UTC

**Comment by pentago** [comment] 2024-09-06 11:30
@nikitabobko this issue is **not** a duplicate.

#57 is about preserving app assignments to monitors while #70 is about setting window layouts and preserving them so they do not get reset after reconnecting to a monitor, reboot or whatever.

For example I have 9 apps that I use daily and when I boot and start Aerospace all those apps gets assigned to their preserved positions - something similar to what [Stay.app](https://apps.apple.com/us/app/stay/id435410196) do.

**Comment by bdlow** [comment] 2024-11-08 04:26
> #57 is about preserving app assignments to monitors while #70 is about setting window layouts and preserving them so they do not get reset after reconnecting to a monitor, reboot or whatever.

#57 specifically asks "Is there a way to persist assignments to workspaces other than adding each individual app to the config? ...  I still want them to remain in the workspaces where I put them after reboots or application restarts"

i.e. this certainly appears to be a duplicate.
