### ISSUE TITLE
Feature Request: Add a way of easliy telling which window has focus

### ISSUE THREAD

**Issue by GraemeARobinson** [nikitabobko/AeroSpace#108] opened 2024-01-10 09:22 UTC
I love aerospace so much!!!

I'm currently using [JankyBorders](https://github.com/FelixKratz/JankyBorders) for this with a blue border drawn around the active window and nothing drawn around inactive windows and it works well but it would be neat if this could be included in aerospace

**Comment by nikitabobko** [comment] 2024-01-10 09:50
Duplicate of #85

**Closed by nikitabobko** 2024-01-10 09:50 UTC
