### ISSUE TITLE
Softly assign workspace to monitor

### ISSUE THREAD

**Issue by Amparose** [nikitabobko/AeroSpace#752] opened 2024-11-24 08:42 UTC
Workspaces with intent is great, i.e. "Workspace (C)omms for email and messaging apps". I _usually_ like this one on Monitor D but sometimes I want to focus it by moving it to Monitor A. To have this flexibility I can't use `workspace-to-monitor-force-assignment` but then I have to manually move all my workspaces into position on every start, which is annoying.

I'd like a `workspace-to-monitor-assignment` (no `force`) that assigns a workspace to a monitor, if it exists, at launch but doesn't force it to stay there. A "reset this workspace to assigned monitor" would be nice to avoid the workspace shuffle of moving one monitor-at-a-time.

**Comment by nikitabobko** [comment] 2024-12-20 10:40
Duplicate of #123

**Closed by nikitabobko** 2024-12-20 10:40 UTC
Labels: feature-proposal, duplicate
