### ISSUE TITLE
Zen browser import

### ISSUE THREAD

**Issue by patrickhuitema** [nikitabobko/AeroSpace#779] opened 2024-11-29 12:03 UTC
##### AeroSpace Runtime Error #####

Please report to:
    https://github.com/nikitabobko/AeroSpace/issues/new
    Please describe what you did to trigger this error

Message: Window(title: 'Optional("Zen Browser")', role: 'Optional("AXWindow")', subrole: 'Optional("AXStandardWindow")', identifier: 'nil', modal: 'Optional("false")', windowId: 'Optional("4740")') is already unbound
Version: 0.16.0-Beta
Git hash: d172dfd8a92f2d339f3d46a12a297e43e80768ca
Coordinate: /Users/bobko/a/AeroSpace/Sources/AppBundle/tree/TreeNode.swift:115:34 unbindFromParent()
recursionDetectorDuringFailure: false
cli: false

Stacktrace:
0   AeroSpace                           0x000000010027b648 $s6Common6errorT_4file4line6column8functionxSS_SSS2iSStlF + 740
1   AeroSpace                           0x000000010011a9bc $s9AppBundle8TreeNodeC16unbindFromParentAA11BindingDataVyF + 236
2   AeroSpace                           0x00000001001151d0 $s9AppBundle9MacWindowC14garbageCollect22skipClosedWindowsCacheySb_tF + 136
3   AeroSpace                           0x00000001000ff9f8 $s9AppBundle9gcWindowsyyF + 500
4   AeroSpace                           0x00000001000faed4 $s9AppBundle14refreshSession26screenIsDefinitelyUnlocked7startup10forceFocus4bodyxSb_S2bxyXEtlFyt_Tg503$s9a32Bundle16refreshAndLayout26screenfG31Unlocked7startupySb_SbtFyyXEfU_Tf1nnnnc_n + 644
5   AeroSpace                           0x00000001001055ac $s9AppBundle10resizedObs_2ax5notif4dataySo13AXObserverRefa_So011AXUIElementI0aSo08CFStringI0aSvSgtFTf4dddn_n + 172
6   HIServices                          0x0000000191712a80 _XXMIGPostNotification + 896
7   HIServices                          0x0000000191743fa0 _XPostNotification + 356
8   HIServices                          0x00000001916f3368 mshMIGPerform + 212
9   CoreFoundation                      0x000000018ae562c8 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 60
10  CoreFoundation                      0x000000018ae561e8 __CFRunLoopDoSource1 + 524
11  CoreFoundation                      0x000000018ae54b48 __CFRunLoopRun + 2248
12  CoreFoundation                      0x000000018ae53bc4 CFRunLoopRunSpecific + 588
13  HIToolbox                           0x00000001962c5f64 RunCurrentEventLoopInMode + 292
14  HIToolbox                           0x00000001962cbd54 ReceiveNextEventCommon + 636
15  HIToolbox                           0x00000001962cbeb8 _BlockUntilNextEventMatchingListInModeWithFilter + 76
16  AppKit                              0x000000018e97f98c _DPSNextEvent + 660
17  AppKit                              0x000000018f2bfddc -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 688
18  AppKit                              0x000000018e972a64 -[NSApplication run] + 480
19  AppKit                              0x000000018e9492e8 NSApplicationMain + 888
20  SwiftUI                             0x00000001b9020340 $s7SwiftUI6runAppys5NeverOSo21NSApplicationDelegate_So11NSResponderCXcFTf4e_nAA07TestingdG0C_Tg5Tm + 160
21  SwiftUI                             0x00000001b9490ee4 $s7SwiftUI6runAppys5NeverOxAA0D0RzlF + 84
22  SwiftUI                             0x00000001b9809f24 $s7SwiftUI3AppPAAE4mainyyFZ + 224
23  AeroSpace                           0x000000010009d3ec main + 36
24  dyld                                0x000000018a9ec274 start + 2840

**Comment by nikitabobko** [comment] 2024-11-29 12:27
Duplicate of #706

**Closed by nikitabobko** 2024-11-29 12:27 UTC
