### ISSUE TITLE
Rust compiling makes Aerospace laggy

### ISSUE THREAD

**Issue by gusinacio** [nikitabobko/AeroSpace#309] opened 2024-07-01 23:38 UTC
While compiling some Rust projects, Aerospace gets unresponsive and lags 10~15 seconds to respond to commands.

This includes changing workspaces, resizing and moving windows to other workspaces.

**Comment by nikitabobko** [comment] 2024-07-02 08:05
Duplicate of #131

**Closed by nikitabobko** 2024-07-02 08:05 UTC
