### ISSUE TITLE
[Feature Request] Swap window position keyboard shortcut

### ISSUE THREAD

**Issue by juniusfree** [nikitabobko/AeroSpace#61] opened 2023-12-17 02:10 UTC
Again, apologies if this can be done already with the current features.

Adding a shortcut to switch windows around would be really helpful. I often change which window is the biggest on my screen to focus on it, like I used to do in [Amethyst](https://ianyh.com/amethyst/).

https://github.com/nikitabobko/AeroSpace/assets/8164667/ab12fd87-3b7d-4073-a9ac-4c76ae199d6d

**Comment by nikitabobko** [comment] 2023-12-17 11:44
Duplicate of #8

**Closed** 2023-12-17 11:44 UTC
