### ISSUE TITLE
Wrong tiling for several windows of the same application "tabbed"

### ISSUE THREAD

**Issue by oscarvarto** [nikitabobko/AeroSpace#277] opened 2024-06-15 06:14 UTC
This is an example of the problem:

![image](https://github.com/nikitabobko/AeroSpace/assets/1676245/813104eb-3c46-4d5f-ae71-54f4c8e5f475)

At the right, I have opened 2 PDFs in Preview.app. So, aeroSpace treats the two PDFs as if they were each occupying its own separate window (and that's why a third of the screen is wasted on a supposedly separate Window for the second PDF document), but the reality is that Preview allows to have "Tabs" to open several documents at the same time.

This is what aeroSpace sees (but actually, the documents should be allowed to be tabbed):
![image](https://github.com/nikitabobko/AeroSpace/assets/1676245/03839b1a-c835-40ad-9411-5010b48229f8)

Same problem occurs if I open IntelliJ with "Tabbed" projects, and the behavior is very annoying (it completely wastes Screen space and does not allow to "fix" the situation.

Is this a known issue? Should I make a configuration change somewhere?

**Comment by oscarvarto** [comment] 2024-06-15 06:16
Another problem is that the mouse is not able to choose the other tab. With aeroSpace turned on, the "active tab" in question refuses to change to the new selected one. It's only possible with a key combination.

**Comment by nikitabobko** [comment] 2024-06-15 06:21
Duplicate of #68

**Closed by nikitabobko** 2024-06-15 06:21 UTC
