### ISSUE TITLE
Tiling breask when window decorations are hidden (qutebrowser)

### ISSUE THREAD

**Issue by 2KAbhishek** [nikitabobko/AeroSpace#305] opened 2024-06-30 19:11 UTC
Hi @nikitabobko thanks a lot for the awesome project, I have been playing around with it for some time and finally switched over from yabai recently.

Everything works great for me other than [qutebrowser](https://github.com/qutebrowser/qutebrowser)

- When I am hiding window decorations for qutebrowser, aerospace starts treating qutebrowser as a floating window.
- Tiling works fine when window decorations are not hidden.

Wanted to ask if there is a way to allow this with a rule / if you have any other ideas.

This is what I used on `yabai` to achieve something similar:

`yabai -m rule --add app="^qutebrowser$" title!="^$" role="AXWindow" subrole="AXDialog" manage=on`

Again, thanks a lot!

ENV: macOS Sonoma, latest aerospace installed with brew

**Comment by nikitabobko** [comment] 2024-06-30 20:39
Duplicate of #276

**Closed by nikitabobko** 2024-06-30 20:39 UTC
