### ISSUE TITLE
Option for mouse to follow focus

### ISSUE THREAD

**Issue by winterscar** [nikitabobko/AeroSpace#126] opened 2024-01-18 15:47 UTC
A feature request:

Set the cursor to the top left of the active window when changing focus with aerospace.

Why is this useful?
Some applications follow the mouse cursor when determining the 'active' monitor, such as 
[warpd](https://github.com/rvaiya/warpd) and [raycast](https://www.raycast.com/). When using Aerospace, I tend not to move my mouse too much,  and therefore these applications appear on the 'wrong' monitor.

**Comment by nikitabobko** [comment] 2024-01-18 16:50
Duplicate of #12

**Closed by nikitabobko** 2024-01-18 16:50 UTC

**Comment by winterscar** [comment] 2024-01-18 17:55
Sorry about that, should've searched first :)

**Comment by kabeero** [comment] 2024-02-16 21:36
AutoRaise seems to be working well for me with AeroSpace:
> https://github.com/sbmpost/AutoRaise

Build and symlink
```sh
sudo ln -s ~/Code/AutoRaise/AutoRaise /usr/local/bin/autoraise
```

**aerospace.toml**
```toml
after-startup-command = [
    'exec-and-forget autoraise',
]
```

**Comment by lucax88x** [comment] 2024-07-23 15:18
If you want to have "mouse follow focus" feature from autoraise remember to enable altTaskSwitcher=true and the warpX and warpY at 0.5 or it won't work.
