### ISSUE TITLE
Application Crashed When Opening Word

### ISSUE THREAD

**Issue by TobiasGrossUL** [nikitabobko/AeroSpace#808] opened 2024-12-04 07:59 UTC
I attached the stacktrace:

`Message: Window(title: 'Optional("Some Document")', role: 'Optional("AXWindow")', subrole: 'Optional("AXStandardWindow")', identifier: 'Optional("_NS:13")', modal: 'Optional("false")', windowId: 'Optional("43597")') is already unbound
Version: 0.16.0-Beta
Git hash: d172dfd8a92f2d339f3d46a12a297e43e80768ca
Coordinate: /Users/bobko/a/AeroSpace/Sources/AppBundle/tree/TreeNode.swift:115:34 unbindFromParent()
recursionDetectorDuringFailure: false
cli: false

Stacktrace:
0   AeroSpace                           0x000000010509b4e8 $s6Common6errorT_4file4line6column8functionxSS_SSS2iSStlF + 712
1   AeroSpace                           0x0000000104f2f9fa $s9AppBundle33restoreClosedWindowsCacheIfNeeded19newlyDetectedWindowSbAA0K0C_tF + 2730
2   AeroSpace                           0x0000000104f1b0a1 $s9AppBundle9MacWindowC3get3app02axD07startupACSgAA0cA0C_So14AXUIElementRefaSbtFZTf4nnnd_n + 2097
3   AeroSpace                           0x0000000104f16ff6 $sSTsE10compactMapySayqd__Gqd__Sg7ElementQzKXEKlFSaySo14AXUIElementRefaG_9AppBundle6WindowCTg503$s9f55Bundle03MacA0C25detectNewWindowsAndGetAll7startupSayAA6h15CGSb_tFAGSgSo14D9RefaXEfU_AI0kF0CSbTf1cn_nTf4ngn_n + 278
4   AeroSpace                           0x0000000104f0e6e3 $s9AppBundle03MacA0C25detectNewWindowsAndGetAll7startupSayAA6WindowCGSb_tF + 243
5   AeroSpace                           0x0000000104efbd4e $s9AppBundle41detectNewWindowsAndAttachThemToWorkspaces33_9D4CAE07A16011BB7304F8F5007BD739LL7startupySb_tF + 414
6   AeroSpace                           0x0000000104ef8f91 $s9AppBundle14refreshSession26screenIsDefinitelyUnlocked7startup10forceFocus4bodyxSb_S2bxyXEtlFyt_Tg503$s9A70Bundle9MacWindowC14garbageCollect22skipClosedWindowsCacheySb_tFyyXEfU_SSTf1nnnnc_n + 785
7   AeroSpace                           0x0000000104f17511 $s9AppBundle9MacWindowC14garbageCollect22skipClosedWindowsCacheySb_tF + 817
8   AeroSpace                           0x0000000104efed2e $s9AppBundle9gcWindowsyyF + 494
9   AeroSpace                           0x0000000104ef94c6 $s9AppBundle14refreshSession26screenIsDefinitelyUnlocked7startup10forceFocus4bodyxSb_S2bxyXEtlFyt_Tg503$s9a32Bundle16refreshAndLayout26screenfG31Unlocked7startupySb_SbtFyyXEfU_Tf1nnnnc_n + 662
10  AeroSpace                           0x0000000104f053b4 $s9AppBundle10resizedObs_2ax5notif4dataySo13AXObserverRefa_So011AXUIElementI0aSo08CFStringI0aSvSgtFTf4dddn_n + 148
11  HIServices                          0x00007ff815f5e743 _XXMIGPostNotification + 889
12  HIServices                          0x00007ff815f8c9c6 _XPostNotification + 320
13  HIServices                          0x00007ff815f408df mshMIGPerform + 179
14  CoreFoundation                      0x00007ff80f6685f9 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
15  CoreFoundation                      0x00007ff80f668530 __CFRunLoopDoSource1 + 534
16  CoreFoundation                      0x00007ff80f66717e __CFRunLoopRun + 2752
17  CoreFoundation                      0x00007ff80f66608e CFRunLoopRunSpecific + 550
18  HIToolbox                           0x00007ff81ad7fec3 RunCurrentEventLoopInMode + 292
19  HIToolbox                           0x00007ff81ad858a4 ReceiveNextEventCommon + 646
20  HIToolbox                           0x00007ff81ad85a42 _BlockUntilNextEventMatchingListInModeWithFilter + 66
21  AppKit                              0x00007ff812f80b7f _DPSNextEvent + 902
22  AppKit                              0x00007ff8139b56b4 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1290
23  AppKit                              0x00007ff812f71c59 -[NSApplication run] + 610
24  AppKit                              0x00007ff812f44f96 NSApplicationMain + 823
25  SwiftUI                             0x00007ff91fdefa41 _NSWindowGetCGDisplayID + 218681
26  SwiftUI                             0x00007ff920132010 SwiftUIGlue2Class + 1373344
27  SwiftUI                             0x00007ff9203cdba8 SwiftUIGlue2Class + 4108344
28  AeroSpace                           0x0000000104e921de main + 30
29  dyld                                0x00007ff80f1f52cd start + 1805
`

**Comment by nikitabobko** [comment] 2024-12-04 10:08
Duplicate of #771

**Closed by nikitabobko** 2024-12-04 10:08 UTC
