### ISSUE TITLE
Workspace manipulation: move workspace to current monitor

### ISSUE THREAD

**Issue by MarcinDominiak** [nikitabobko/AeroSpace#338] opened 2024-07-27 13:38 UTC
I'm moving my setup from xmonad to aerospace config and one command/flow which I'm missing is "display workspace X on the currently focused monitor".

Use case: I like to have several workspaces, each with a dedicated "view" for performing specific tasks and I would like to be be able to quickly move desired workspace to the monitor that I'm already looking at. This is convenient when using one monitor, but not with multiple.

I think that `move-workspace-to-monitor` doesn't work for this case as it only allows moving a workspace already with focus to a an adjecent monitor.

I'd imagine this would require a new command like `move-workspace-to-focused-monitor <workspace-name>`, but please let me know if this can be achieved with the current set of commands.

**Comment by nikitabobko** [comment] 2024-07-27 19:36
Duplicate of #186 

I plan to support it in the following way: `move-workspace-to-monitor --workspace 1 focused`

**Closed by nikitabobko** 2024-07-27 19:36 UTC

**Comment by nikitabobko** [comment] 2024-10-13 12:24
Implemented as separate command: `summon-workspace`

Released in 0.15.0
