### ISSUE TITLE
Float dialogs in current workspace

### ISSUE THREAD

**Issue by fmasa** [nikitabobko/AeroSpace#89] opened 2024-01-02 08:35 UTC
Would it be possible to float new dialogs in current workspace?

My use case:
When working without external monitor I have Intellij IDEA on workspace 2, but when I use external monitor, I manually move it to workspace 1 (I use ultrawide monitor) next to my browser.

But when I use it this way, every time some action opens a dialog from IDEA, it is floated in workspace 2.

I currently work around this by not using automatic workspace assignment for IDEA, but would love to re-enable it. Alternatively this can be accomplished by some monitor conditions for window callbacks (so I can automatically assign IDEA to different workspace e.g. when monitor resolution matches the one of the external monitor, but I still think that opening dialogs on same workspace may be useful (I sometimes move windows to different workspaces) 🤔

**Comment by nikitabobko** [comment] 2024-01-02 18:55
Can't reproduce

I tried the following:
1. Open IntelliJ on workspace 1
2. Attach second monitor (workspace 1 is moved to attached monitor. IntelliJ is moved as well because it belongs to workspace 1)
3. Open IntelliJ "Rebase..." dialog

The dialog is shown on the attached monitor as expected 
`AeroSpace v0.7.1-Beta 0e139ec43648b65587393fdee2ce6ca3c8deb997`

**Comment by fmasa** [comment] 2024-01-03 09:22
@nikitabobko I just noticed that this does not happen for anything else than various settings windows. Is it possible that these aren't treated as dialogs?

**Reproduction (without need for external monitor):**

1. Add this rule to .aerospace.toml:
```toml
[[on-window-detected]]
if.app-id = 'com.jetbrains.intellij'
run = 'move-node-to-workspace 2'
```
2. Open IDEA
3. Move IDEA to workspace 1
4. Open Settings from by clicking `Intellij IDEA -> Settings` in main panel

**Expected behavior:**
Settings dialog is opened on workspace 1

**Current behavior:**
Settings dialog is opened on workspace 2 and workspace 2 is opened as current workspace

**Comment by nikitabobko** [comment] 2024-01-03 10:06
> Is it possible that these aren't treated as dialogs?

That won't help. What you want to is to ignore callbacks for dialogs

The workaround you can do right now is`if.during-aerospace-startup = true`

But maybe it would be nice to have `if.is-dialog` condition in the callback

**Comment by fmasa** [comment] 2024-01-05 13:03
@nikitabobko It seems like the Settings window is not recognized as dialog. As you mentioned, regular dialogs work correctly and are not moved to different workspace.

**Comment by nikitabobko** [comment] 2024-01-06 13:28
> It seems like the Settings window is not recognized as dialog

Do you mean that IntelliJ IDEA Settings window is not floated by default? Well, on my machine it is floated. 

Anyway, please open a new issue regarding this problem. It would be helpful if you could attach the screenshot of "Accessibility Inspector.app" (like [I did here](https://github.com/nikitabobko/AeroSpace/issues/47#issuecomment-1850801404))

**Comment by nikitabobko** [comment] 2024-01-06 13:50
I'm closing this issue in favor of #103

**Closed by nikitabobko** 2024-01-06 13:50 UTC
