### ISSUE TITLE
Feature request: Move all nodes to workspace 

### ISSUE THREAD

**Issue by FriedSnowman** [nikitabobko/AeroSpace#363] opened 2024-08-07 19:18 UTC
I've been using Aerospace for a few months now and I think this is something that's missing (unless it's possible somehow and I totally missed it in which case I'm sorry). Right now it's not possible to interact with the nodes in a workspace level, so I have to `move-node-to-workspace` every node in the workspace, switch to that workspace, and then reorganize the layout again.

### Hypothetical use case: 
You have a mental picture set where `Workspace 1` is for your primary task, `Workspace 2` is secondary and so on. The task being performed on `Workspace 2` becomes irrelevant, so it has to give way somehow.

### Suggested implementations:
- Option 1: `switch-workspace-with`
Effectively renames the active workspace with the specified one.
- Option 2: `move-node-to-workspace` accepts optional parameter `--all` with `horizontal` or `vertical`
Take all nodes of the active workspace and merge with the specified one.

**Comment by nikitabobko** [comment] 2024-08-10 18:44
Duplicate of #245

**Closed by nikitabobko** 2024-08-10 18:44 UTC

**Comment by nikitabobko** [comment] 2024-08-10 18:50
Also see related discussion #310 

Given your mental model of workspaces being represented as an ordered array of tasks, I'm curious how you switch workspaces. I guess you use `workspace (next|prev)` and you don't jump to specific workspaces by names, am I right?

Would a command like `workspace --index 2` make sense in your workflow? Imagine you dropped `workspace 2` because it is no longer relevant, `workspace --index 2` would lead you to the next after the previously existed `workspace 2`

**Comment by FriedSnowman** [comment] 2024-08-10 19:15
Yeah I tried searching for duplicate issues but I guess the query wasn't good enough. Oops

I don't ever use 'workspace back and forth'. I remember spaces by their name and associated muscle memory. For instance, 'Workspace G' being Github, and 'Workspace C' being ChatGPT. My normal tasks reside in numbered workspaces depending on the priority. 

So one use case of moving the workspace as a whole would be to display something on the sidecar display, which is force assigned to 'Workspace Caps'. If I need to work with Github, I would want to change out the contents of 'Workspace Caps' with 'Workspace G'. The reason I don't set the sidecar to 'Workspace G' is because of muscle memory and confusion.
