### ISSUE TITLE
Remember last workspaces of windows upon starting AeroSpace

### ISSUE THREAD

**Issue by edgimar** [nikitabobko/AeroSpace#356] opened 2024-08-04 22:36 UTC
Here's the user-experience I would like to improve:

1. User opens 30 windows, and has them distributed in a particular way across 10 workspaces.
2. AeroSpace is closed for some reason, and then re-opened.
3. All 30 windows are on workspace 0.

At the least, can the associated workspace of each window be tracked in some persistent way (periodically saved, and saved when closing/crashing?), so that when AeroSpace is started again, all of these open windows can be re-assigned to the workspace they were last on?

Or maybe there is already a way to do this that I'm unaware of?

**Comment by nikitabobko** [comment] 2024-08-04 22:53
Duplicate of #57

**Closed by nikitabobko** 2024-08-04 22:53 UTC

**Comment by edgimar** [comment] 2024-08-09 21:10
It isn't clear to me if #57 is a duplicate or not -- this issue is about automatically storing whatever the current workspace is, and restoring later on if starting up.  It seems like #57 is about layouts (which doesn't matter here, where we just want the windows on the correct workspaces), and about specific layouts / workspaces that in general will not change.

This issue is more like how when you quit chrome and have 5 different windows with different tabs in each window, when you start it up again (if you have the config option enabled), all windows open up again with all tabs in their respective windows.  It's about taking a current snapshot and restoring it later on (if the window exists at the time that AeroSpace is started).
