### ISSUE TITLE
Feature: add focus-cycle command

### ISSUE THREAD

**Issue by velppa** [nikitabobko/AeroSpace#566] opened 2024-10-05 07:10 UTC
Hello, I started using AeroSpace and it's an impressive window manager!  

One thing I miss is ability to cycle focus of windows, like Emacs' "M-x other-window" command. Commands "focus left|right|up|down" stop when they reach the boundary.  So users forced to have four keybindings instead of one and should think where they should go. In Emacs I have "alt-o" mapped to "other-window" and pressing it several times until I end up in the desired window (I rarely have more than 3) is so much better.  I want to have similar binding in AeroSpace mapped to the same key, so "alt-h, j, k, l" are free.

The implementation might be DFS over the window tree.

## Checklist

- [x] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
  - focus cycle
- [x] I've read the guide https://nikitabobko.github.io/AeroSpace/guide
- [x] I've searched in the documentation (https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands). My search queries were:
  - focus
  - monitor

```
λ aerospace --version
aerospace CLI client version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
AeroSpace.app server version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
```

**Comment by nikitabobko** [comment] 2024-10-05 19:46
Duplicate of #248

**Closed by nikitabobko** 2024-10-05 19:46 UTC
