### ISSUE TITLE
Feature request: change layout mode depending on the number of open windows

### ISSUE THREAD

**Issue by patmuk** [nikitabobko/AeroSpace#261] opened 2024-06-09 07:26 UTC
Hi,

usually I have the same arrangement of windows. It would be great if this could be configured, so I don't have to press any positioning keys.
For example, on my external monitor I usually do:

First the windows next to each other (h-tiles)
1 | 2 | 3
1 | 2 | 3
When a 4th window opens, the 3rd should v-tile join-with:
1 | 2 | 3
1 | 2 | 4
And the next windows as well:
1 | 2 | 3
1 | 5 | 4

1 | 2 | 3
6 | 5 | 4

As an extended feature, while on a small (=Laptop monitor), it should be
1 | 2
1 | 2

1 | 2
1 | 3

1 | 2
4 | 3

It would be great, if this could be configured, for example:
switch-layout 4 vertical
(meaning, from the 4th window on, switch the layout to vertical)
and
switch-layout-on-monitor <monitor-ID> 4 vertical

**Comment by nikitabobko** [comment] 2024-06-09 09:40
Duplicate of #260

**Closed by nikitabobko** 2024-06-09 09:40 UTC

**Comment by patmuk** [comment] 2024-06-09 14:26
Ok, if #260 meant the same, I am glad!
The key point here is an automatically changed layout depending on the number of open windows, not the workspace.
