### ISSUE TITLE
Provide a command to print the layout tree

### ISSUE THREAD

**Issue by jlargentaye** [nikitabobko/AeroSpace#257] opened 2024-06-07 18:47 UTC
For a beginner, the implicitness of containers can make it confusing to understand why windows are being organized in a particular way. For example, I couldn't understand why my editor window wasn't tiling with a terminal window, until I realized I had accidentally made the editor window `floating`, and even so it wasn't clear where in the layout tree it was.

I wished I had a command that could dump the layout tree, which would have helped me understand what was going on.

**Comment by llimllib** [comment] 2024-06-07 19:20
I'm not a contributor to the project, but I'm pretty sure this is the last open todo from #16 

I'm just here because I would really like this too, and had searched and found that issue.

(I'm having a lot of fun using aerospace but not being able to see the tree makes it like learning with a blindfold on!)

**Comment by nikitabobko** [comment] 2024-06-08 12:30
Duplicate of #16

**Closed by nikitabobko** 2024-06-08 12:30 UTC
