### ISSUE TITLE
Aerospace crashes after a few minutes of operation

### ISSUE THREAD

**Issue by tsraveling** [nikitabobko/AeroSpace#819] opened 2024-12-05 22:27 UTC
## Environment

Macbook Pro M3, Sonoma
~15 windows open

## Bug

After working well for a few minutes, Aerospace crashes with the following log:

```
##### AeroSpace Runtime Error #####

Please report to:
    https://github.com/nikitabobko/AeroSpace/issues/new
    Please describe what you did to trigger this error

Message: 
Version: 0.16.1-Beta
Git hash: 7b88c46da8b00dcde023ec41f9629d19e0024902
Coordinate: /Users/bobko/a/AeroSpace/Sources/AppBundle/tree/frozen/closedWindowsCache.swift:48:10 cacheClosedWindowIfNeeded(window:)
recursionDetectorDuringFailure: false
cli: false
Displays have separate spaces: true

Stacktrace:
0   AeroSpace                           0x0000000102fffbc8 $s6Common6errorT_4file4line6column8functionxSS_SSS2iSStlFs5NeverO_Tg5 + 1100
1   AeroSpace                           0x000000010302b328 $s6Common5check__4file4line6column8functionySb_SSyXKSSS2iSStF + 92
2   AeroSpace                           0x0000000102edc564 $s9AppBundle25cacheClosedWindowIfNeeded6windowyAA0E0C_tF + 1116
3   AeroSpace                           0x0000000102ec3cf8 $s9AppBundle9MacWindowC14garbageCollect22skipClosedWindowsCacheySb_tF + 136
4   AeroSpace                           0x0000000102eaed80 $s9AppBundle9gcWindowsyyF + 500
5   AeroSpace                           0x0000000102eac7ac $s9AppBundle2gc33_9D4CAE07A16011BB7304F8F5007BD739LLyyF + 388
6   AeroSpace                           0x0000000102ea9574 $s9AppBundle14refreshSession26screenIsDefinitelyUnlocked7startup4bodyxSb_SbxyXEtlFyt_Tg503$s9a32Bundle16refreshAndLayout26screenfG31Unlocked7startupySb_SbtFyyXEfU_Tf1nnnc_n + 272
7   HIServices                          0x00000001a1ad63b0 _XXMIGPostNotification + 896
8   HIServices                          0x00000001a1b0149c _XPostNotification + 360
9   HIServices                          0x00000001a1ab8340 mshMIGPerform + 208
10  CoreFoundation                      0x000000019b6a2a6c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 60
11  CoreFoundation                      0x000000019b6a298c __CFRunLoopDoSource1 + 524
12  CoreFoundation                      0x000000019b6a1350 __CFRunLoopRun + 2244
13  CoreFoundation                      0x000000019b6a0434 CFRunLoopRunSpecific + 608
14  HIToolbox                           0x00000001a5e4419c RunCurrentEventLoopInMode + 292
15  HIToolbox                           0x00000001a5e43fd8 ReceiveNextEventCommon + 648
16  HIToolbox                           0x00000001a5e43d30 _BlockUntilNextEventMatchingListInModeWithFilter + 76
17  AppKit                              0x000000019eeffd68 _DPSNextEvent + 660
18  AppKit                              0x000000019f6f5808 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 700
19  AppKit                              0x000000019eef309c -[NSApplication run] + 476
20  AppKit                              0x000000019eeca2e0 NSApplicationMain + 880
21  SwiftUI                             0x00000001c703e474 OUTLINED_FUNCTION_12 + 13968
22  SwiftUI                             0x00000001c77a7e88 OUTLINED_FUNCTION_3 + 196
23  SwiftUI                             0x00000001c7ba2eb8 OUTLINED_FUNCTION_0 + 140
24  AeroSpace                           0x0000000102e4cfd0 main + 36
25  dyld                                0x000000019b23a0e0 start + 2360
```

**Comment by nikitabobko** [comment] 2024-12-05 22:28
Duplicate of #818

**Closed by nikitabobko** 2024-12-05 22:28 UTC
Labels: bug, duplicate
