### ISSUE TITLE
`aerospace` command speed

### ISSUE THREAD

**Issue by samholmes** [nikitabobko/AeroSpace#407] opened 2024-08-13 22:23 UTC
I setup `skhd` with the following config:

```
:: default : say -v Daniel "boop"
:: aero : say -v Daniel "beep"

rctrl - return ; aero

aero < escape ; default

aero < h : aerospace focus left
aero < j : aerospace focus down
aero < k : aerospace focus up
aero < l : aerospace focus right
```

When using this setup, the commands do run, but there is significant lag. Is this lag caused by skhd, bash or aerospace?

**Comment by nikitabobko** [comment] 2024-08-14 09:06
Duplicate of #104

**Closed by nikitabobko** 2024-08-14 09:06 UTC
