### ISSUE TITLE
Windows layout issues

### ISSUE THREAD

**Issue by hevzy86** [nikitabobko/AeroSpace#733] opened 2024-11-21 07:03 UTC
Hello, i have 2 external monitors setup and  sometimes i have this type of issues with layout, looks like it leaves some extra space for invisible tile. Could it be because i have some "floating windows"? Thank you

<img width="1512" alt="Screenshot 2024-11-20 at 8 02 38 PM" src="https://github.com/user-attachments/assets/cbd1a686-605d-4f35-9126-ca4f3f9b39a9">
<img width="675" alt="Screenshot 2024-11-20 at 1 26 34 PM" src="https://github.com/user-attachments/assets/58a313b5-9d6e-4c3c-bfac-d32693d20c60">
<img width="1349" alt="Screenshot 2024-11-20 at 12 48 56 PM" src="https://github.com/user-attachments/assets/fddc3dad-3a63-4353-bb26-08dcf6a07b54">

**Comment by mrkskk** [comment] 2024-11-21 13:24
It happens when mac interprents a tab as a window.


For example it happens with finder. disable that new finder windows open as tabs to solve it.

For me it still happens randomly, but 
`ctrl-alt-cmd-semicolon =  'balance-sizes'` usually solves it for me

**Comment by hevzy86** [comment] 2024-11-21 13:48
Thank you very much, I'm gonna try it  👍

**Comment by hevzy86** [comment] 2024-11-21 19:49
Hello, unfortunately it didn't help: i tried:
ctrl-alt-cmd-semicolon =  'balance-sizes'

alt-shift-semicolon = 'mode service'
r = ['flatten-workspace-tree', 'mode main'] 

but i found why it happens - when i close/quit an app it creates this issue, is there any resolution to avoid / fix it?

**Comment by RollerMatic** [comment] 2024-11-21 21:23
I think you should attach details about your OS (type, version) and aerospace version to this issue. 
I have a similar issue to yours, and balance-sizes doesn't do anything for me. I do have "Displays have seperate spaces" turned on though so not sure if that's impacting anything.
aerospace details:

aerospace CLI client version: 0.15.2-Beta b6cf82771f245ab7349a93baf8709e171537ff58
AeroSpace.app server version: 0.15.2-Beta b6cf82771f245ab7349a93baf8709e171537ff58

Running on macos sequoia 15.1.1

The cli does have a debug-windows functionality which i am playing around with but it's not clear to me (yet) how I am supposed to use this information. What would be useful is for aerospace to provide a -v flag (or similar) to enable debug logging about what the subcmd is doing

**Comment by hevzy86** [comment] 2024-11-21 21:47
"Displays have seperate spaces" turned on 

macos sequoia 15.1

aerospace CLI client version: 0.15.2-Beta b6cf82771f245ab7349a93baf8709e171537ff58
AeroSpace.app server version: 0.15.2-Beta b6cf82771f245ab7349a93baf8709e171537ff58

[New_aerospace.txt](https://github.com/user-attachments/files/17852376/New_aerospace.txt)

**Comment by hevzy86** [comment] 2024-11-21 22:16
by the way when i'm trying to navigate on windows i see how cursor moves on empty space, like there are several windows which i don't see, any ideas?

**Comment by hevzy86** [comment] 2024-11-22 04:08
I figured out what's the issue, it happens when i'm closing an app with keyboard or red cross button- it creates this gap, then i should go to dock and quit it form there - then this gap disappear
is there any aerospace keyboard shortcut  i could assign to perform it? Couldn't find it in docs

**Comment by nikitabobko** [comment] 2024-11-22 13:46
Duplicate of #445

**Closed by nikitabobko** 2024-11-22 13:46 UTC
Labels: bug

**Comment by YarivLevy81** [comment] 2025-01-28 21:18
Anyone able so solve it in Sequoia? Recently changed from yabai, the only thing i'm missing is an easy balance of sizes which doesn't seem to work
