### ISSUE TITLE
Is there a BSP mode in aerospace?

### ISSUE THREAD

**Issue by sameer1612** [nikitabobko/AeroSpace#384] opened 2024-08-12 06:58 UTC
Like in Yabai, if I open a window can it do a binary partition(master-child) and put a new window and split the parent in half?

Creating a container and placing windows seems an overkill for simple and repeated layouts like:

<img width="132" alt="image" src="https://github.com/user-attachments/assets/e37163d2-fd85-477a-ba0f-17987d437dc0">

**Comment by nikitabobko** [comment] 2024-08-12 09:40
Duplicate of #260

**Closed by nikitabobko** 2024-08-12 09:40 UTC
