### ISSUE TITLE
Is it possible to list the current tree layout?

### ISSUE THREAD

**Issue by jdhuntington** [nikitabobko/AeroSpace#495] opened 2024-09-06 15:03 UTC
Is it possible to list the current tree layout? I'm finding that I'm not intuiting where windows will go when I execute a command,  and I'm hoping to see the structure of my layout while I'm still learning. Is there something like i3's `get_tree` that I could run?

## Checklist

- [X] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
  - list tree
  - `get_tree`
- [X] I've read the documentation https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands
- [X] I've searched in the documentation. My search queries were:
  - tree
  - list tree

**Comment by nikitabobko** [comment] 2024-09-28 19:26
Duplicate of #16

**Closed by nikitabobko** 2024-09-28 19:26 UTC
