### ISSUE TITLE
Incorrect window and workspace focus with multiple monitor

### ISSUE THREAD

**Issue by paulodiovani** [nikitabobko/AeroSpace#229] opened 2024-05-16 20:08 UTC
If I have more than one of the same application distributed across monitors, when I switch workspaces, the last opened window of that application gets focused instead of the one on the focused workspace/monitor.

## Detailed explanation

- I have two monitors
- My primary monitor hosts workspaces 1-9, while the secondary have workspace 10
- I have keybindings to switch workspaces using `cmd` (e.g. `cmd-1 = workspace 1`)

### Steps to reproduce

1. Open an application (e.g. Firefox) on the `workspace 1` (primary monitor)
2. Open another window of the same application in `workspace 10` (secondary monitor)
3. Open another application (e.g. Terminal) on the `workspace 2` (primary monitor)
4. Switch to `workspace 1` (e.g. type `cmd-1`)
5. Switch to `workspace 2` (e.g. type `cmd-1`)
6. Switch to `workspace 1` I need your GD account to start enabling the rest of the permissions

### Expected behavior

Window on `workspace 1` is focused

### Current behavior

Window on `workspace 10` is focused, even though I focused `workspace 1`

### Workaround

By focusing `workspace 1` again (e.g. typing `cmd-1` twice) the correct window gets focus.

## System information

```
OS: macOS 14.1.2 23B2091 arm64
Host: Mac15,6
Kernel: 23.1.0
Uptime: 38 days, 4 hours, 16 mins
Packages: 158 (brew)
Shell: zsh 5.9
Resolution: 1920x1080, 1512x982
DE: Aqua
WM: Quartz Compositor
WM Theme: Purple (Dark)
Terminal: tmux
CPU: Apple M3 Pro
GPU: Apple M3 Pro
Memory: 3408MiB / 18432MiB
```

```
aerospace CLI client version: 0.10.0-Beta 4fe8276262b8df077ffface84c3f93f1b832b8ac
AeroSpace.app server version: 0.10.0-Beta 4fe8276262b8df077ffface84c3f93f1b832b8ac
```

**Comment by nikitabobko** [comment] 2024-05-17 04:59
It's a known and unfortunate problem. It's a bug in Apple API. The workaround is to disable "Displays have separate spaces"

**Comment by nikitabobko** [comment] 2024-05-17 04:59
Duplicate of #101

**Closed by nikitabobko** 2024-05-17 04:59 UTC
