### ISSUE TITLE
Crash on window close and unlock

### ISSUE THREAD

**Issue by Mineinjava** [nikitabobko/AeroSpace#802] opened 2024-12-03 21:32 UTC
Not sure exactly what happened here. I locked my macbook (not logout). When I unlocked again, my discord window had closed and I got the following log.

```
##### AeroSpace Runtime Error #####

Please report to:
    https://github.com/nikitabobko/AeroSpace/issues/new
    Please describe what you did to trigger this error

Message: Window(title: 'Optional("@<CENSOREDUSERNAME> - Discord")', role: 'Optional("AXWindow")', subrole: 'Optional("AXStandardWindow")', identifier: 'nil', modal: 'Optional("false")', windowId: 'Optional("4919")') is already unbound
Version: 0.16.0-Beta
Git hash: d172dfd8a92f2d339f3d46a12a297e43e80768ca
Coordinate: /Users/bobko/a/AeroSpace/Sources/AppBundle/tree/TreeNode.swift:115:34 unbindFromParent()
recursionDetectorDuringFailure: false
cli: false

Stacktrace:
0   AeroSpace                           0x0000000104913648 $s6Common6errorT_4file4line6column8functionxSS_SSS2iSStlF + 740
1   AeroSpace                           0x00000001047c3324 $s9AppBundle33restoreClosedWindowsCacheIfNeeded19newlyDetectedWindowSbAA0K0C_tF + 2548
2   AeroSpace                           0x00000001047b0c28 $s9AppBundle9MacWindowC3get3app02axD07startupACSgAA0cA0C_So14AXUIElementRefaSbtFZTf4nnnd_n + 1648
3   AeroSpace                           0x00000001047acfa0 $sSTsE10compactMapySayqd__Gqd__Sg7ElementQzKXEKlFSaySo14AXUIElementRefaG_9AppBundle6WindowCTg503$s9f55Bundle03MacA0C25detectNewWindowsAndGetAll7startupSayAA6h15CGSb_tFAGSgSo14D9RefaXEfU_AI0kF0CSbTf1cn_nTf4ngn_n + 248
4   AeroSpace                           0x00000001047a57ac $s9AppBundle03MacA0C25detectNewWindowsAndGetAll7startupSayAA6WindowCGSb_tF + 256
5   AeroSpace                           0x00000001047955d0 $s9AppBundle41detectNewWindowsAndAttachThemToWorkspaces33_9D4CAE07A16011BB7304F8F5007BD739LL7startupySb_tF + 384
6   AeroSpace                           0x0000000104792f30 $s9AppBundle14refreshSession26screenIsDefinitelyUnlocked7startup10forceFocus4bodyxSb_S2bxyXEtlFyt_Tg503$s9a32Bundle16refreshAndLayout26screenfG31Unlocked7startupySb_SbtFyyXEfU_Tf1nnnnc_n + 736
7   AeroSpace                           0x0000000104737824 $s9AppBundle14GlobalObserverC7onNotif33_F1205CFDC13498282252A689C79131F6LLyy10Foundation12NotificationVFZTf4nd_n + 384
8   AeroSpace                           0x0000000104736b08 $s10Foundation12NotificationVIeghn_So14NSNotificationCIeyBhy_TR + 116
9   CoreFoundation                      0x0000000191d227ec __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 128
10  CoreFoundation                      0x0000000191db366c ___CFXRegistrationPost_block_invoke + 88
11  CoreFoundation                      0x0000000191db35b4 _CFXRegistrationPost + 436
12  CoreFoundation                      0x0000000191cf143c _CFXNotificationPost + 732
13  Foundation                          0x0000000192e99b14 -[NSNotificationCenter postNotificationName:object:userInfo:] + 88
14  AppKit                              0x00000001959f15ec applicationStatusSubsystemCallback + 728
15  LaunchServices                      0x00000001921c7e84 ___LSScheduleNotificationFunction_block_invoke_2 + 52
16  CoreFoundation                      0x0000000191d2d8c0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 28
17  CoreFoundation                      0x0000000191d2d7d0 __CFRunLoopDoBlocks + 356
18  CoreFoundation                      0x0000000191d2cc00 __CFRunLoopRun + 2432
19  CoreFoundation                      0x0000000191d2bbc4 CFRunLoopRunSpecific + 588
20  HIToolbox                           0x000000019d19df64 RunCurrentEventLoopInMode + 292
21  HIToolbox                           0x000000019d1a3d54 ReceiveNextEventCommon + 636
22  HIToolbox                           0x000000019d1a3eb8 _BlockUntilNextEventMatchingListInModeWithFilter + 76
23  AppKit                              0x000000019585798c _DPSNextEvent + 660
24  AppKit                              0x0000000196197ddc -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 688
25  AppKit                              0x000000019584aa64 -[NSApplication run] + 480
26  AppKit                              0x00000001958212e8 NSApplicationMain + 888
27  SwiftUI                             0x00000001bfef7340 $s7SwiftUI6runAppys5NeverOSo21NSApplicationDelegate_So11NSResponderCXcFTf4e_nAA07TestingdG0C_Tg5Tm + 160
28  SwiftUI                             0x00000001c0367ee4 $s7SwiftUI6runAppys5NeverOxAA0D0RzlF + 84
29  SwiftUI                             0x00000001c06e0f24 $s7SwiftUI3AppPAAE4mainyyFZ + 224
30  AeroSpace                           0x00000001047353ec main + 36
31  dyld                                0x00000001918c4274 start + 2840
```

**Comment by nikitabobko** [comment] 2024-12-04 10:08
Duplicate of https://github.com/nikitabobko/AeroSpace/issues/771

**Closed by nikitabobko** 2024-12-04 10:08 UTC
Labels: bug, duplicate
