### ISSUE TITLE
pin float windows?

### ISSUE THREAD

**Issue by m1guer** [nikitabobko/AeroSpace#608] opened 2024-10-22 18:12 UTC
**YOUR TEXT**

how can i pin float windows? to see the window in all avaibles workspace?

## Checklist

- [x] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
  - aerospace pin float windows
  - pin window
- [x] I've read the guide https://nikitabobko.github.io/AeroSpace/guide
- [x] I've searched in the documentation (https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands). My search queries were:
  - pin
  - float
  - workspaces
```
aerospace CLI client version: 0.15.2-Beta b6cf82771f245ab7349a93baf8709e171537ff58
AeroSpace.app server version: 0.15.2-Beta b6cf82771f245ab7349a93baf8709e171537ff58
```

**Comment by nikitabobko** [comment] 2024-10-22 18:34
Duplicate of #2

**Closed by nikitabobko** 2024-10-22 18:34 UTC
