### ISSUE TITLE
Feature Request: Accept optional <window-id> argument for some commands.

### ISSUE THREAD

**Issue by hahuang65** [nikitabobko/AeroSpace#295] opened 2024-06-21 16:36 UTC
I currently use a "hidden" workspace to toss floating windows into, and the summon them back out with a hotkey.

However, `move-node-to-workspace` requires the window to be focused, which means  `focus <window-id>` will focus the "hidden" workspace first. It's a bit jarring from a UX perspective.

Would it be possible for `move-node-to-workspace` to take an optional argument for `<window-id>`?

This could extend out to a few other commands as well, any of the `move-*` commands, maybe some others.

**Comment by nikitabobko** [comment] 2024-06-21 18:11
Duplicate of #186

**Closed by nikitabobko** 2024-06-21 18:11 UTC
