### ISSUE TITLE
[Feature Resquest] Add target window to move-node-to-workspace

### ISSUE THREAD

**Issue by iures** [nikitabobko/AeroSpace#531] opened 2024-09-23 13:52 UTC
Currently, move-node-to-workspace only allow us to move the focused window. I would like to add the capability to use a specific window, which might not even be in the current workspace. 

The main use case that I have is that I can quickly implement a quick query in a program like Alfred or similar and be able to bring a window from a different workspace to the current one.

I appreciate the consideration!

## Checklist
- [x] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
  - move window
  - move-node-to-workspace
- [x] I've read the guide https://nikitabobko.github.io/AeroSpace/guide
- [x] I've searched in the documentation (https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands). My search queries were:
  - move-node-to-workspace

```
aerospace CLI client version: 0.14.1-Beta 5861e85b65cb7dc914a0a68027c56e2bc90510fd
AeroSpace.app server version: 0.14.1-Beta 5861e85b65cb7dc914a0a68027c56e2bc90510fd
```

**Comment by nikitabobko** [comment] 2024-09-23 13:53
Duplicate of #186

**Closed by nikitabobko** 2024-09-23 13:53 UTC
