### ISSUE TITLE
ASI found [libswiftCore.dylib] (sensitive) 'Common/commonUtil.swift:42: Fatal error: 

### ISSUE THREAD

**Issue by yanfosec** [nikitabobko/AeroSpace#343] opened 2024-07-29 13:15 UTC
ASI found [libswiftCore.dylib] (sensitive) 'Common/commonUtil.swift:42: Fatal error: 
Please report to:
    https://github.com/nikitabobko/AeroSpace/issues/new

Message: 
Version: 0.13.2-Beta
Git hash: 8ec4ac8ed61a55984ab950a9e662cc63018219fa
Coordinate: /Users/bobko/a/AeroSpace/Sources/AppBundle/focus.swift:93:18 focusWorkspace()
recursionDetectorDuringFailure: true
cli: false

Stacktrace:
0   AeroSpace                           0x0000000102ef3480 $s6Common6errorT_4file4line6column8functionxSS_SSS2iSStlFs5NeverO_Tg5 + 740
1   AeroSpace                           0x0000000102f10fbc $s6Common5check__4file4line6column8functionySb_S2SS2iSStF + 56
2   AeroSpace                           0x0000000102d85dd4 $s9AppBundle9WorkspaceC05focusC0SbyF + 164
3   AeroSpace                           0x0000000102d4ac00 $s9AppBundle26MoveNodeToWorkspaceCommandV4_run_5stdinSbAA0G12MutableStateC_SStFTf4nnx_n + 1072
4   AeroSpace                           0x0000000102d3c360 $sSa9AppBundleAA7Command_pRszlE4_run33_432A18ED58CEF<…>'

**Comment by nikitabobko** [comment] 2024-07-29 14:14
Duplicate of https://github.com/nikitabobko/AeroSpace/issues/341

**Closed by nikitabobko** 2024-07-29 14:14 UTC
