### ISSUE TITLE
Crash on focusing another monitor

### ISSUE THREAD

**Issue by zgagnon** [nikitabobko/AeroSpace#803] opened 2024-12-03 21:53 UTC
**Describe the bug**
When I clicked on a window on another monitor. Started after updating Aerospace on 2 December

**Related issues you could find**
Other recent crashes:
- https://github.com/nikitabobko/AeroSpace/issues/802
- https://github.com/nikitabobko/AeroSpace/issues/771

**Crash Report** 
##### AeroSpace Runtime Error #####

Message: Window(title: 'Optional("")', role: 'nil', subrole: 'nil', identifier: 'nil', modal: 'Optional("")', windowId: 'Optional("5076")') is already unbound
Version: 0.16.0-Beta
Git hash: d172dfd8a92f2d339f3d46a12a297e43e80768ca
Coordinate: /Users/bobko/a/AeroSpace/Sources/AppBundle/tree/TreeNode.swift:115:34 unbindFromParent()
recursionDetectorDuringFailure: false
cli: false

Stacktrace:
0   AeroSpace                           0x0000000100d47648 $s6Common6errorT_4file4line6column8functionxSS_SSS2iSStlF + 740
1   AeroSpace                           0x0000000100be69bc $s9AppBundle8TreeNodeC16unbindFromParentAA11BindingDataVyF + 236
2   AeroSpace                           0x0000000100be11d0 $s9AppBundle9MacWindowC14garbageCollect22skipClosedWindowsCacheySb_tF + 136
3   AeroSpace                           0x0000000100bcb9f8 $s9AppBundle9gcWindowsyyF + 500
4   AeroSpace                           0x0000000100bc6968 $s9AppBundle14refreshSession26screenIsDefinitelyUnlocked7startup10forceFocus4bodyxSb_S2bxyXEtlFyt_Tg503$s9A70Bundle9MacWindowC14garbageCollect22skipClosedWindowsCacheySb_tFyyXEfU_SSTf1nnnnc_n + 660
5   AeroSpace                           0x0000000100be1410 $s9AppBundle9MacWindowC14garbageCollect22skipClosedWindowsCacheySb_tF + 712
6   AeroSpace                           0x0000000100bcb9f8 $s9AppBundle9gcWindowsyyF + 500
7   AeroSpace                           0x0000000100bc905c $s9AppBundle12refreshModelyyF + 388
8   AeroSpace                           0x0000000100bc6fb8 $s9AppBundle14refreshSession26screenIsDefinitelyUnlocked7startup10forceFocus4bodyxSb_S2bxyXEtlFyt_Tg503$s9a32Bundle16refreshAndLayout26screenfG31Unlocked7startupySb_SbtFyyXEfU_Tf1nnnnc_n + 872
9   AeroSpace                           0x0000000100bd0130 $s9AppBundle8movedObs_2ax5notif4dataySo13AXObserverRefa_So011AXUIElementI0aSo08CFStringI0aSvSgtFTf4dddn_n + 172
10  HIServices                          0x000000019b4d5a80 _XXMIGPostNotification + 896
11  HIServices                          0x000000019b506fa0 _XPostNotification + 356
12  HIServices                          0x000000019b4b6368 mshMIGPerform + 212
13  CoreFoundation                      0x0000000194c1a2c8 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 60
14  CoreFoundation                      0x0000000194c1a1e8 __CFRunLoopDoSource1 + 524
15  CoreFoundation                      0x0000000194c18b48 __CFRunLoopRun + 2248
16  CoreFoundation                      0x0000000194c17bc4 CFRunLoopRunSpecific + 588
17  HIToolbox                           0x00000001a0087f64 RunCurrentEventLoopInMode + 292
18  HIToolbox                           0x00000001a008dd54 ReceiveNextEventCommon + 636
19  HIToolbox                           0x00000001a008deb8 _BlockUntilNextEventMatchingListInModeWithFilter + 76
20  AppKit                              0x0000000198743a08 _DPSNextEvent + 660
21  AppKit                              0x0000000199083e0c -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 688
22  AppKit                              0x0000000198736ae0 -[NSApplication run] + 480
23  AppKit                              0x000000019870d364 NSApplicationMain + 888
24  SwiftUI                             0x00000001c2dbd340 $s7SwiftUI6runAppys5NeverOSo21NSApplicationDelegate_So11NSResponderCXcFTf4e_nAA07TestingdG0C_Tg5Tm + 160
25  SwiftUI                             0x00000001c322dee4 $s7SwiftUI6runAppys5NeverOxAA0D0RzlF + 84
26  SwiftUI                             0x00000001c35a6f24 $s7SwiftUI3AppPAAE4mainyyFZ + 224
27  AeroSpace                           0x0000000100b693ec main + 36
28  dyld                                0x00000001947b0274 start + 2840

**Comment by nikitabobko** [comment] 2024-12-04 10:11
Duplicate of #706

**Closed by nikitabobko** 2024-12-04 10:11 UTC
Labels: bug
