### ISSUE TITLE
🚀[FEA]: Ignore certain apps or window classes

### ISSUE THREAD

**Issue by akshaysubr** [nikitabobko/AeroSpace#17] opened 2023-11-14 05:38 UTC
Aerospace is really fantastic, but with any tiling wm, I always run into an issue with Microsoft Teams. Specifically, when you're on a teams call and you switch mac spaces or Aerospace workspaces, Teams decides to pop up a new tiny meeting preview window. There doesn't seem to be a way to prevent this behavior in Teams, but some way of ignoring this in AeroSpace would be really great! Maybe something like i3's `for_window [class="Microsoft Teams ..."]`?

The specific issue I am running into is that this preview Teams window pops up for a second causing the existing windows to resize to adjust for it but then disappears after a second before reappearing after another second and so on. This makes all the other windows unusable. However, this does not happen when switching from the original Teams workspace to another workspace. It only happens reproducibly when switching from Teams to a second workspace and then to a third non-Teams workspace.

**Comment by nikitabobko** [comment] 2023-11-14 07:54
Duplicate of #15

**Closed by nikitabobko** 2023-11-14 07:54 UTC
