### ISSUE TITLE
Reverse Orientation of Display Numbering

### ISSUE THREAD

**Issue by samarthm314** [nikitabobko/AeroSpace#381] opened 2024-08-12 00:31 UTC
I'm using sketchybar as an indicator to show spaces for each of my monitors. However I'm having an issue with the spaces getting swapped because my secondary display is position on the left. Secondary is assigned 1, primary is assigned 2. If I swap the virtual location to the right of the primary it behaves as intended. Is there an easy way to flip the number assignment to right to left vs left to right in the toml file?

**Comment by nikitabobko** [comment] 2024-08-12 00:46
Duplicate of #336

**Closed by nikitabobko** 2024-08-12 00:46 UTC

**Comment by samarthm314** [comment] 2024-08-12 01:09
Sorry I'm new to this type of stuff; what was the fix?

**Comment by agenttank** [comment] 2024-08-13 06:02
your issue is already known and is being worked on in #336 @samarthm314 

I hope for a fix too for my 3 monitor setup 

for my 2 monitor setup it helped to just set the other display to being my main screen in MacOS settings

**Comment by samarthm314** [comment] 2024-08-13 18:54
Ok, thank you!
