### ISSUE TITLE
Feature request: alternative config file location

### ISSUE THREAD

**Issue by SoloSynth1** [nikitabobko/AeroSpace#67] opened 2023-12-19 21:04 UTC
First of all, thank you so much for creating AeroSpace. It is a nice fresh breath of air coming from yabai + skhd, have been loving it so far.

Currently the config file `.aerospace.toml` needs to be stored in the home folder. While it is not particularly irksome, it does add to the large list of dotfiles in the home folder to make things a little bit more cluttered.

I'm wondering would it be possible for Aerospace to support alternative config location such as `.config/aerospace/aerospace.toml`? Thank you.

Edit: typo

**Comment by nikitabobko** [comment] 2023-12-20 11:27
Duplicate of #21

**Closed by nikitabobko** 2023-12-20 11:27 UTC
