### ISSUE TITLE
Use numerical order of spaces (1, 2, 3 ..., 10)  instead of lexicographical (1, 10, 2, 3, 4)

### ISSUE THREAD

**Issue by danieltomasz** [nikitabobko/AeroSpace#259] opened 2024-06-07 22:54 UTC
I disabled spaces assigned to letters, I have now only ten spaces, but they are ordered in the lexicographical order (1, 10, 2 ...)
 instead of ordering them by their value (1, 2, 3... 10) 

I have 2 screens -  my active workspaces after restarting aerospace have active spaces 1 and 10.
![image](https://github.com/nikitabobko/AeroSpace/assets/7980381/0ae293d4-d60f-4b91-a0e3-44acefcd7475)
I consider this as a bug.

**Comment by nikitabobko** [comment] 2024-06-08 12:29
Duplicate of #162 

And no, I don't consider it as a bug

**Closed by nikitabobko** 2024-06-08 12:29 UTC
