### ISSUE TITLE
Move an Entire Node

### ISSUE THREAD

**Issue by chasingtheflow** [nikitabobko/AeroSpace#284] opened 2024-06-18 05:56 UTC
Hey,

Is there a way to move an Entire node instead of just the window?

ie Can I go from 

h_tiles
├── window 1
└── v_tiles (focused)
    ├── window 2
    └── window 3

To 

h_tiles
└── v_tiles (focused)
    ├── window 2
    └── window 3
├── window 1 

If feels like this should be trivial but I can't quite grasp how to do it without moving with multiple motions. Maybe what I'm asking is can I focus a node and then move the whole node the same way I would move a single window.

**Comment by nikitabobko** [comment] 2024-06-18 08:10
Duplicate of #5

**Closed by nikitabobko** 2024-06-18 08:10 UTC
