### ISSUE TITLE
Workspace "10" automatically created & Can't have two different workspaces on two monitors

### ISSUE THREAD

**Issue by kaynetik** [nikitabobko/AeroSpace#541] opened 2024-09-29 07:34 UTC
I've copied the default config.

At the moment I'm facing two issues, of which one is clearly visible. `AeroSpace` is creating automatically a workspace number 10, which can't be switched to.

![image](https://github.com/user-attachments/assets/8d16fdee-7652-41e5-86b9-c3c6f4b1bc8d)

Another issue I'm facing, which might be related to the one above is that I can't have different workspaces open on each of my monitors, e.g., having ws-B on the monitor on my right, and ws-2 on my left monitor.

## Checklist

- [x] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
  - 10
  https://github.com/nikitabobko/AeroSpace/issues/522
  This issue was neglected because person reporting didn't follow the template.
- [x] I've read the guide https://nikitabobko.github.io/AeroSpace/guide
- [x] I've searched in the documentation (https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands). My search queries were:
  - multi-monitor support
  - deleting a workspace

```
aerospace CLI client version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
AeroSpace.app server version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
```

**Comment by kaynetik** [comment] 2024-09-29 08:24
After a second read of the docs I've realized that `[workspace-to-monitor-force-assignment]` is what enables me to define which ws would go where, as they are all int the same bucket.

Though first issue with ws "10" still persists.

**Comment by nikitabobko** [comment] 2024-09-29 09:01
Duplicate of #222

**Closed by nikitabobko** 2024-09-29 09:01 UTC

**Comment by kaynetik** [comment] 2024-09-29 09:04
True, after I played with the config a bit more I've realized that 🤦🏼
