### ISSUE TITLE
[Questions] How to resize & move floating windows? 

### ISSUE THREAD

**Issue by nuynait** [nikitabobko/AeroSpace#487] opened 2024-09-02 18:00 UTC
It seems that I am not able to use any of the following keys / commends to resize a floating window. 

```
minus = 'resize smart -200'
equal = 'resize smart +200'
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
```

They work perfectly for windows in the tile, but does not work for floating windows. Here is a quick screencast:

https://github.com/user-attachments/assets/d3d5a077-33b2-46b6-9ae7-23b3053bd19d

I wonder if this is actually on purpose that the resize command won't work for floating windows? If that is is there a way I can resize the floating window with keybindings? 

Also is it possible to move the floating window up, down, left and right on screen with keybindings? 

Is there a way to config as: when I trigger a window to float, I can config it to display in the middle of the screen with a specific width and height? 

Thank you for assisting me in resolving my inquiries. I look forward to your response.

## Checklist

- [x] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
  - resize floating 
  - resize
  - move window
- [x] I've read the documentation https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands
- [x] I've searched in the documentation. My search queries were:
  - resize
  - floating
  - move (command seems only move from window between tiles which not applicable to the floating window)

```
aerospace CLI client version: 0.14.1-Beta 5861e85b65cb7dc914a0a68027c56e2bc90510fd
AeroSpace.app server version: 0.14.1-Beta 5861e85b65cb7dc914a0a68027c56e2bc90510fd
```

**Comment by nikitabobko** [comment] 2024-09-02 18:09
Duplicate of #9

**Closed by nikitabobko** 2024-09-02 18:09 UTC

**Comment by nuynait** [comment] 2024-09-02 18:11
Sorry 🙇‍♂️ Not sure why I missed that issue when I searching the issue list. Apologize for the interruption.
