### ISSUE TITLE
Crash Report for /Users/bobko/a/AeroSpace/Sources/AppBundle/tree/TreeNode.swift:115:34 unbindFromParent()

### ISSUE THREAD

**Issue by aaftre** [nikitabobko/AeroSpace#799] opened 2024-12-02 21:16 UTC
**Describe the bug**
Returned to desk found this crash report. - probably occurs when unplugging external monitor

```text
##### AeroSpace Runtime Error #####

Please report to:
    https://github.com/nikitabobko/AeroSpace/issues/new
    Please describe what you did to trigger this error

Message: Window(title: 'Optional("...")', role: 'Optional("AXWindow")', subrole: 'Optional("AXStandardWindow")', identifier: 'nil', modal: 'Optional("false")', windowId: 'Optional("211919")') is already unbound
Version: 0.16.0-Beta
Git hash: d172dfd8a92f2d339f3d46a12a297e43e80768ca
Coordinate: /Users/bobko/a/AeroSpace/Sources/AppBundle/tree/TreeNode.swift:115:34 unbindFromParent()
recursionDetectorDuringFailure: false
cli: false

Stacktrace:
0   AeroSpace                           0x0000000103167648 $s6Common6errorT_4file4line6column8functionxSS_SSS2iSStlF + 740
1   AeroSpace                           0x0000000103017324 $s9AppBundle33restoreClosedWindowsCacheIfNeeded19newlyDetectedWindowSbAA0K0C_tF + 2548
2   AeroSpace                           0x0000000103004c28 $s9AppBundle9MacWindowC3get3app02axD07startupACSgAA0cA0C_So14AXUIElementRefaSbtFZTf4nnnd_n + 1648
3   AeroSpace                           0x0000000103000fa0 $sSTsE10compactMapySayqd__Gqd__Sg7ElementQzKXEKlFSaySo14AXUIElementRefaG_9AppBundle6WindowCTg503$s9f55Bundle03MacA0C25detectNewWindowsAndGetAll7startupSayAA6h15CGSb_tFAGSgSo14D9RefaXEfU_AI0kF0CSbTf1cn_nTf4ngn_n + 248
4   AeroSpace                           0x0000000102ff97ac $s9AppBundle03MacA0C25detectNewWindowsAndGetAll7startupSayAA6WindowCGSb_tF + 256
5   AeroSpace                           0x0000000102fe95d0 $s9AppBundle41detectNewWindowsAndAttachThemToWorkspaces33_9D4CAE07A16011BB7304F8F5007BD739LL7startupySb_tF + 384
6   AeroSpace                           0x0000000102fe69c4 $s9AppBundle14refreshSession26screenIsDefinitelyUnlocked7startup10forceFocus4bodyxSb_S2bxyXEtlFyt_Tg503$s9A70Bundle9MacWindowC14garbageCollect22skipClosedWindowsCacheySb_tFyyXEfU_SSTf1nnnnc_n + 752
7   AeroSpace                           0x0000000103001410 $s9AppBundle9MacWindowC14garbageCollect22skipClosedWindowsCacheySb_tF + 712
8   AeroSpace                           0x0000000102feb9f8 $s9AppBundle9gcWindowsyyF + 500
9   AeroSpace                           0x0000000102fe6ed4 $s9AppBundle14refreshSession26screenIsDefinitelyUnlocked7startup10forceFocus4bodyxSb_S2bxyXEtlFyt_Tg503$s9a32Bundle16refreshAndLayout26screenfG31Unlocked7startupySb_SbtFyyXEfU_Tf1nnnnc_n + 644
10  AeroSpace                           0x0000000102ff15ac $s9AppBundle10resizedObs_2ax5notif4dataySo13AXObserverRefa_So011AXUIElementI0aSo08CFStringI0aSvSgtFTf4dddn_n + 172
11  HIServices                          0x00000001a4c35a80 _XXMIGPostNotification + 896
12  HIServices                          0x00000001a4c66fa0 _XPostNotification + 356
13  HIServices                          0x00000001a4c16368 mshMIGPerform + 212
14  CoreFoundation                      0x000000019e37a2c8 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 60
15  CoreFoundation                      0x000000019e37a1e8 __CFRunLoopDoSource1 + 524
16  CoreFoundation                      0x000000019e378b48 __CFRunLoopRun + 2248
17  CoreFoundation                      0x000000019e377bc4 CFRunLoopRunSpecific + 588
18  HIToolbox                           0x00000001a97e7f64 RunCurrentEventLoopInMode + 292
19  HIToolbox                           0x00000001a97edd54 ReceiveNextEventCommon + 636
20  HIToolbox                           0x00000001a97edeb8 _BlockUntilNextEventMatchingListInModeWithFilter + 76
21  AppKit                              0x00000001a1ea3a08 _DPSNextEvent + 660
22  AppKit                              0x00000001a27e3e0c -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 688
23  AppKit                              0x00000001a1e96ae0 -[NSApplication run] + 480
24  AppKit                              0x00000001a1e6d364 NSApplicationMain + 888
25  SwiftUI                             0x00000001cc51c340 $s7SwiftUI6runAppys5NeverOSo21NSApplicationDelegate_So11NSResponderCXcFTf4e_nAA07TestingdG0C_Tg5Tm + 160
26  SwiftUI                             0x00000001cc98cee4 $s7SwiftUI6runAppys5NeverOxAA0D0RzlF + 84
27  SwiftUI                             0x00000001ccd05f24 $s7SwiftUI3AppPAAE4mainyyFZ + 224
28  AeroSpace                           0x0000000102f893ec main + 36
29  dyld                                0x000000019df10274 start + 2840
```

**Comment by aaftre** [comment] 2024-12-02 22:55
probably another instance of the same thing.

occurs when unplugging external monitor

```text
##### AeroSpace Runtime Error #####

Please report to:
    https://github.com/nikitabobko/AeroSpace/issues/new
    Please describe what you did to trigger this error

Message: Window(title: 'Optional("‎WhatsApp")', role: 'Optional("AXWindow")', subrole: 'Optional("AXStandardWindow")', identifier: 'Optional("SceneWindow")', modal: 'Optional("false")', windowId: 'Optional("211833")') is already unbound
Version: 0.16.0-Beta
Git hash: d172dfd8a92f2d339f3d46a12a297e43e80768ca
Coordinate: /Users/bobko/a/AeroSpace/Sources/AppBundle/tree/TreeNode.swift:115:34 unbindFromParent()
recursionDetectorDuringFailure: false
cli: false

Stacktrace:
0   AeroSpace                           0x0000000100b0f648 $s6Common6errorT_4file4line6column8functionxSS_SSS2iSStlF + 740
1   AeroSpace                           0x00000001009bf324 $s9AppBundle33restoreClosedWindowsCacheIfNeeded19newlyDetectedWindowSbAA0K0C_tF + 2548
2   AeroSpace                           0x00000001009acc28 $s9AppBundle9MacWindowC3get3app02axD07startupACSgAA0cA0C_So14AXUIElementRefaSbtFZTf4nnnd_n + 1648
3   AeroSpace                           0x00000001009a8fa0 $sSTsE10compactMapySayqd__Gqd__Sg7ElementQzKXEKlFSaySo14AXUIElementRefaG_9AppBundle6WindowCTg503$s9f55Bundle03MacA0C25detectNewWindowsAndGetAll7startupSayAA6h15CGSb_tFAGSgSo14D9RefaXEfU_AI0kF0CSbTf1cn_nTf4ngn_n + 248
4   AeroSpace                           0x00000001009a17ac $s9AppBundle03MacA0C25detectNewWindowsAndGetAll7startupSayAA6WindowCGSb_tF + 256
5   AeroSpace                           0x00000001009915d0 $s9AppBundle41detectNewWindowsAndAttachThemToWorkspaces33_9D4CAE07A16011BB7304F8F5007BD739LL7startupySb_tF + 384
6   AeroSpace                           0x000000010098ef30 $s9AppBundle14refreshSession26screenIsDefinitelyUnlocked7startup10forceFocus4bodyxSb_S2bxyXEtlFyt_Tg503$s9a32Bundle16refreshAndLayout26screenfG31Unlocked7startupySb_SbtFyyXEfU_Tf1nnnnc_n + 736
7   AeroSpace                           0x00000001009995ac $s9AppBundle10resizedObs_2ax5notif4dataySo13AXObserverRefa_So011AXUIElementI0aSo08CFStringI0aSvSgtFTf4dddn_n + 172
8   HIServices                          0x00000001a4c35a80 _XXMIGPostNotification + 896
9   HIServices                          0x00000001a4c66fa0 _XPostNotification + 356
10  HIServices                          0x00000001a4c16368 mshMIGPerform + 212
11  CoreFoundation                      0x000000019e37a2c8 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 60
12  CoreFoundation                      0x000000019e37a1e8 __CFRunLoopDoSource1 + 524
13  CoreFoundation                      0x000000019e378b48 __CFRunLoopRun + 2248
14  CoreFoundation                      0x000000019e377bc4 CFRunLoopRunSpecific + 588
15  HIToolbox                           0x00000001a97e7f64 RunCurrentEventLoopInMode + 292
16  HIToolbox                           0x00000001a97edbb4 ReceiveNextEventCommon + 220
17  HIToolbox                           0x00000001a97edeb8 _BlockUntilNextEventMatchingListInModeWithFilter + 76
18  AppKit                              0x00000001a1ea3a08 _DPSNextEvent + 660
19  AppKit                              0x00000001a27e3e0c -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 688
20  AppKit                              0x00000001a1e96ae0 -[NSApplication run] + 480
21  AppKit                              0x00000001a1e6d364 NSApplicationMain + 888
22  SwiftUI                             0x00000001cc51c340 $s7SwiftUI6runAppys5NeverOSo21NSApplicationDelegate_So11NSResponderCXcFTf4e_nAA07TestingdG0C_Tg5Tm + 160
23  SwiftUI                             0x00000001cc98cee4 $s7SwiftUI6runAppys5NeverOxAA0D0RzlF + 84
24  SwiftUI                             0x00000001ccd05f24 $s7SwiftUI3AppPAAE4mainyyFZ + 224
25  AeroSpace                           0x00000001009313ec main + 36
26  dyld                                0x000000019df10274 start + 2840
```

**Comment by nikitabobko** [comment] 2024-12-03 10:16
Duplicate of #771

**Closed by nikitabobko** 2024-12-03 10:16 UTC
Labels: bug
