### ISSUE TITLE
Crash with 0.13.2

### ISSUE THREAD

**Issue by DieracDelta** [nikitabobko/AeroSpace#344] opened 2024-07-29 13:23 UTC
Stack trace: 

```
##### AeroSpace Runtime Error #####

Please report to:
    https://github.com/nikitabobko/AeroSpace/issues/new

Message: 
Version: 0.13.2-Beta
Git hash: 8ec4ac8ed61a55984ab950a9e662cc63018219fa
Coordinate: /Users/bobko/a/AeroSpace/Sources/AppBundle/focus.swift:93:18 focusWorkspace()
recursionDetectorDuringFailure: false
cli: false

Stacktrace:
0   AeroSpace                           0x0000000102f77480 $s6Common6errorT_4file4line6column8functionxSS_SSS2iSStlFs5NeverO_Tg5 + 740
1   AeroSpace                           0x0000000102f94fbc $s6Common5check__4file4line6column8functionySb_S2SS2iSStF + 56
2   AeroSpace                           0x0000000102e09dd4 $s9AppBundle9WorkspaceC05focusC0SbyF + 164
3   AeroSpace                           0x0000000102dcec00 $s9AppBundle26MoveNodeToWorkspaceCommandV4_run_5stdinSbAA0G12MutableStateC_SStFTf4nnx_n + 1072
4   AeroSpace                           0x0000000102dc0360 $sSa9AppBundleAA7Command_pRszlE4_run33_432A18ED58CEF2DADA210F47D7D5B974LL_5stdinSbAA0C12MutableStateC_SStF + 1052
5   AeroSpace                           0x0000000102df2b1c $s9AppBundle12activateModeyySSSgFyycfU0_yyXEfU_ + 456
6   AeroSpace                           0x0000000102e0fb58 $s9AppBundle14refreshSession7startup10forceFocus4bodyxSb_SbxyXEtlFyt_Tg503$s9A41Bundle12activateModeyySSSgFyycfU0_yyXEfU_SSAA13HotkeyBindingVTf1nnnc_n + 828
7   AeroSpace                           0x0000000103033684 $s6HotKey0A14KeysControllerC17handleCarbonEventys5Int32Vs13OpaquePointerVSgFZTf4nd_n + 336
8   HIToolbox                           0x0000000197f40444 _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 1232
9   HIToolbox                           0x0000000197f3f844 _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 356
10  HIToolbox                           0x0000000197f55cd8 SendEventToEventTarget + 40
11  AppKit                              0x00000001918186c8 -[NSApplication(NSEventRouting) sendEvent:] + 1252
12  AppKit                              0x000000019146689c -[NSApplication _handleEvent:] + 60
13  AppKit                              0x00000001910170c0 -[NSApplication run] + 512
14  AppKit                              0x0000000190fee2e0 NSApplicationMain + 880
15  SwiftUI                             0x00000001b9162474 OUTLINED_FUNCTION_12 + 13968
16  SwiftUI                             0x00000001b98cbe88 OUTLINED_FUNCTION_3 + 196
17  SwiftUI                             0x00000001b9cc6eb8 OUTLINED_FUNCTION_0 + 140
18  AeroSpace                           0x0000000102db8ce0 main + 36
19  dyld                                0x000000018d35e0e0 start + 2360
```

Config file:
```
# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# Feel free to omit keys that you don't use in your config.
# If the key is absent in your config the default value is taken from this config

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands.html
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands.html
after-startup-command = []

# Start AeroSpace at login
start-at-login = false

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide.html#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide.html#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide.html#assign-workspaces-to-monitors
gaps.inner.horizontal = 0
gaps.inner.vertical =   0
gaps.outer.left =       0
gaps.outer.bottom =     0
gaps.outer.top =        0
gaps.outer.right =      0

# Visual indent makes it easier to understand that containers of the same orientation are nested.
# If you have 'enable-normalization-opposite-orientation-for-nested-containers' enabled then
# there is no way to observe the indent
# indent-for-nested-containers-with-the-same-orientation = 30

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide.html#binding-modes
# 'main' binding mode must be always presented
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands.html

# You can uncomment this line to open up terminal with alt + enter shortcut
# See: https://nikitabobko.github.io/AeroSpace/commands.html#exec-and-forget
# alt-enter = 'exec-and-forget open -n /System/Applications/Utilities/Terminal.app'
alt-enter = 'exec-and-forget open -n /Applications/Ghostty.app'
# alt-shift-enter = 'exec-and-forget emacsclient -c --socket-name testing --no-wait'
alt-shift-enter = 'exec-and-forget "/Users/jrestivo/flakes/run_emacs.sh"'

# See: https://nikitabobko.github.io/AeroSpace/commands.html#layout
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands.html#focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands.html#move
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands.html#resize
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# See: https://nikitabobko.github.io/AeroSpace/commands.html#workspace
alt-0 = 'workspace 0'
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-a = 'workspace A'
alt-b = 'workspace B'
alt-c = 'workspace C'
alt-d = 'workspace D'
alt-e = 'workspace E'
alt-f = 'workspace F'
alt-g = 'workspace G'
alt-i = 'workspace I'
alt-m = 'workspace M'
alt-n = 'workspace N'
alt-o = 'workspace O'
alt-p = 'workspace P'
alt-q = 'workspace Q'
# alt-r = 'workspace R'
alt-s = 'workspace S'
alt-t = 'workspace T'
alt-u = 'workspace U'
alt-v = 'workspace V'
alt-w = 'workspace W'
alt-x = 'workspace X'
alt-y = 'workspace Y'
alt-z = 'workspace Z'

# See: https://nikitabobko.github.io/AeroSpace/commands.html#move-node-to-workspace
alt-shift-0 = 'move-node-to-workspace 0'
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-a = 'move-node-to-workspace A'
alt-shift-b = 'move-node-to-workspace B'
alt-shift-c = 'move-node-to-workspace C'
alt-shift-d = 'move-node-to-workspace D'
alt-shift-e = 'move-node-to-workspace E'
alt-shift-f = 'move-node-to-workspace F'
alt-shift-g = 'move-node-to-workspace G'
alt-shift-i = 'move-node-to-workspace I'
alt-shift-m = 'move-node-to-workspace M'
alt-shift-n = 'move-node-to-workspace N'
alt-shift-o = 'move-node-to-workspace O'
alt-shift-p = 'move-node-to-workspace P'
alt-shift-q = 'move-node-to-workspace Q'
# alt-shift-r = 'move-node-to-workspace R'
alt-shift-s = 'move-node-to-workspace S'
alt-shift-t = 'move-node-to-workspace T'
alt-shift-u = 'move-node-to-workspace U'
alt-shift-v = 'move-node-to-workspace V'
alt-shift-w = 'move-node-to-workspace W'
alt-shift-x = 'move-node-to-workspace X'
alt-shift-y = 'move-node-to-workspace Y'
alt-shift-z = 'move-node-to-workspace Z'

# See: https://nikitabobko.github.io/AeroSpace/commands.html#workspace-back-and-forth
alt-tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands.html#move-workspace-to-monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# See: https://nikitabobko.github.io/AeroSpace/commands.html#mode
alt-shift-semicolon = 'mode service'
alt-shift-slash = 'mode join'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide.html#binding-modes
[mode.service.binding]
r = ['flatten-workspace-tree', 'mode main'] # reset layout
#s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']
esc = ['reload-config', 'mode main']

# 'join' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide.html#binding-modes
[mode.join.binding]
ctrl-shift-h = ['join-with left', 'mode main']
ctrl-shift-j = ['join-with down', 'mode main']
ctrl-shift-k = ['join-with up', 'mode main']
ctrl-shift-l = ['join-with right', 'mode main']
esc = 'mode main'

[workspace-to-monitor-force-assignment]
1 = 1
2 = 1
3 = 1
4 = 2
5 = 2
6 = 2
7 = [3, 1]
8 = [3, 1]
9 = [3, 1]
0 = [3, 1]
```

OS version: Sonoma 14.5

Repro: aerospace reproducibly crashes within a few seconds of starting up. I start aerospace, move some of my windows to different workspaces with shortcuts (e.g. mod+shift+1, mod+shift+2 etc) and aerospace will consistently crash.

**Comment by nikitabobko** [comment] 2024-07-29 14:13
Duplicate of #341

**Closed by nikitabobko** 2024-07-29 14:13 UTC
