### ISSUE TITLE
Feature request: restore-size command

### ISSUE THREAD

**Issue by karadnik-flutterint** [nikitabobko/AeroSpace#282] opened 2024-06-17 13:37 UTC
Hi, I want to propose a `restore-size` command

**Use case:** When i messed up the resizing of my tilings, i want to be able to restore it back to every app taking the same space in the respective parent.

**Alternative approaches:**

Use `flatten-workspace-tree` - it does resize all apps back to taking same amount of space, but it also resets the layout to only one parent and I need to recreate my layout.
 
**Synopsis:**

USAGE: restore-size [-h|--help] 
OPTIONS:
  -h, --help             Print help

I am not a swift guy at all, but I am willing to work on this feature if it will be useful, Let me know!

**Comment by nikitabobko** [comment] 2024-06-17 22:34
Duplicate of #114

**Closed by nikitabobko** 2024-06-17 22:34 UTC
