### ISSUE TITLE
Support no notch padding for simple fullscreen mode

### ISSUE THREAD

**Issue by diocletiann** [nikitabobko/AeroSpace#78] opened 2023-12-30 20:24 UTC
Toggling simple fullscreen mode in apps that use the entire screen (like alacritty) moves the window down below the notch and obscures the bottom of the window.

**Comment by nikitabobko** [comment] 2024-01-01 19:30
Sorry, the issue is unclear.

It's not possible to move windows above the notch, they immediately jump below the notch. How do you want AeroSpace to put windows above the notch?

**Comment by diocletiann** [comment] 2024-01-02 02:54
Ideally, if an application chooses to draw over the notch (to the top edge), is should be allow to do so.

**Comment by nikitabobko** [comment] 2024-01-02 03:18
Can you please specify what feature flag of alacritty allows that?

**Comment by diocletiann** [comment] 2024-01-02 03:22
`ToggleSimpleFullscreen`

**Comment by nikitabobko** [comment] 2024-01-02 19:48
Reproduced. Next time, please provide more details on your issues, steps to reproduce, and screenshots.

Frankly speaking, I'm not sure that Alacritty is doing the right thing. They should account for the notch. Right now, the notch overlays the terminal output. I'd consider opening an issue in their tracker

> Ideally, if an application chooses to draw over the notch (to the top edge), it should be allow to do so.

I don't think it's possible to reliably detect if the app wants to draw itself above the notch. At least I don't know how

You can write an automation (using aerospace CLI) that makes the window float, and runs the Alacritty action `ToggleSimpleFullscreen`

Since I think that it can't be fixed on AeroSpace side, I am closing the issue. If somebody manages to fix it, PRs are welcome

**Closed by nikitabobko** 2024-01-02 19:48 UTC

**Comment by diocletiann** [comment] 2024-01-02 20:20
Sure I'll provide more details next time, I just assumed this was a well known feature. It's intentional to maximize screen space, especially with using a terminal editor. Kitty, Ghostty, and others have the same option. Yabai also doesn't interfere with this behavior.
