### ISSUE TITLE
Discord window close issues

### ISSUE THREAD

**Issue by ubuntudroid** [nikitabobko/AeroSpace#77] opened 2023-12-30 19:19 UTC
Discord seems to behave strange when closing the window.

The following example shows the issue nicely. This is the starting configuration, with Discord being on the far right:

![CleanShot 2023-12-30 at 20 12 25](https://github.com/nikitabobko/AeroSpace/assets/519867/a8a639d2-81b4-4d22-9f77-b2234b8c17cc)

1. When closing the window via the macOS shortcut CMD+W (or by pressing the red button in the menu bar) the window will close, but the empty space reserved for the window remains:  ![CleanShot 2023-12-30 at 20 13 20](https://github.com/nikitabobko/AeroSpace/assets/519867/2cceb49e-f121-47fa-aaf4-6fc27a6b1eed)
2. When closing the window via my self-assigned shortcut which simply executes the Aerospace 'close' command, the window seems to be opened again automatically right after being closed: 

https://github.com/nikitabobko/AeroSpace/assets/519867/798a1178-2184-4ec7-ae13-167601b7ada0

The only way to get the proper behavior is to quit Discord, but that's rarely what I want.

**Comment by nikitabobko** [comment] 2023-12-30 20:30
Reproduced

It's because Discord hides the app instead of closing the window. What a creative way to close windows... I admire you, Discord 🤦

**Comment by nikitabobko** [comment] 2023-12-30 20:30
Marking the issue as duplicate of #18

**Closed by nikitabobko** 2023-12-30 20:30 UTC

**Comment by ubuntudroid** [comment] 2023-12-30 21:53
Oh well, guess I'll then also simply move Discord to a "hide" workspace instead, just as recommended in https://github.com/nikitabobko/AeroSpace/issues/18#issuecomment-1869202503.
