### ISSUE TITLE
Unplugging secondary monitor results in 2 visible workspaces on main monitor (although only 1 is visible)

### ISSUE THREAD

**Issue by iphoneintosh** [nikitabobko/AeroSpace#404] opened 2024-08-13 18:03 UTC
Step to reproduce:
- Use aerospace with two monitors: `main` and `secondary`
- Workspaces 1,2,3 are assigned to `main` monitor, workspaces 4,5,6 are assigned to `secondary` monitor
- On `main` monitor, workspace 1 is focused, on `secondary` monitor, workspace 4 is focused
- Executing `aerospace list-workspaces --visible --monitor 1` returns (as expected) `1`
- Executing `aerospace list-workspaces --visible --monitor 2` returns (as expected) `4`
- Now, the `secondary` monitor is unplugged, the `main` monitor remains focused on workspace `1`
- `aerospace list-workspaces --visible --monitor 1` returns two focused workspaces: `1 \n 4` (-> bug since it should only return `1`)

**Comment by nikitabobko** [comment] 2024-08-13 20:35
Duplicate of #268

**Closed by nikitabobko** 2024-08-13 20:35 UTC
