### ISSUE TITLE
My dialogs tend to open in the background

### ISSUE THREAD

**Issue by JonasVautherin** [nikitabobko/AeroSpace#323] opened 2024-07-08 18:53 UTC
Some (many?) of my dialog windows tend to appear in the background, meaning that I tend to miss them if I don't expect a dialog (and if I do, I need to actively search for it).

Even when a dialog appears, its floating behaviour means that clicking on another window will move the dialog to the back again (so I will "lose" it).

Is there a way to force dialogs to be tiled (that is what I expect in i3wm or Sway), or to somehow "pin" them (such that they always stay in the foreground)?

**Comment by nikitabobko** [comment] 2024-07-08 18:58
Duplicate of #4

**Closed by nikitabobko** 2024-07-08 18:58 UTC

**Comment by JonasVautherin** [comment] 2024-07-08 19:03
Also note that it is apparently possible to force tiling all windows [with something like this](https://nikitabobko.github.io/AeroSpace/guide#dialog-heuristics):

```
[[on-window-detected]]
check-further-callbacks = true
run = 'layout tiling'
```
