### ISSUE TITLE
CLI command to retrieve the current workspace of the focused window

### ISSUE THREAD

**Issue by mike1808** [nikitabobko/AeroSpace#39] opened 2023-12-04 23:51 UTC
Hey! I'm asking for the following cli command which returns the active workspace of the focused window.

I'm trying to attach trackpad gestures to go through workspaces like native ones through BetterTouchTool but for that I need to retrieve the current one to know which is next in my order.

**Comment by nikitabobko** [comment] 2023-12-04 23:55
Duplicate of #16

**Closed by nikitabobko** 2023-12-04 23:55 UTC
