### ISSUE TITLE
Unwanted window animation

### ISSUE THREAD

**Issue by MatthiasGrandl** [nikitabobko/AeroSpace#51] opened 2023-12-13 07:42 UTC
I don't have Accessibility Options enabled. Sometimes when I am switching spaces, the window on the space flies in from the bottom right corner. Quitting the application and restarting fixes the issue temporarily.

Attached a small recording showing the issue:

https://github.com/nikitabobko/AeroSpace/assets/50196894/059c583d-3ba1-4efb-b5c9-3a2226775ccc

**Comment by MatthiasGrandl** [comment] 2023-12-13 07:47
Ah nevermind I had reduced motion enabled. Just disabled it, if the issue doesn't reoccur, I would suggest adding it to the other specifically mentioned Accessibility Options, as I assume this is one that a lot of potention AeroSpace users have enabled.

**Comment by MatthiasGrandl** [comment] 2023-12-13 08:04
Nope disabling reduced motion did not fix it :(

**Comment by fmasa** [comment] 2023-12-13 09:53
I noticed this with specific windows. For me this never happens for any app except Firefox, Firefox animates every time (when moving window and when switching to a workspace with Firefox)

**Comment by nikitabobko** [comment] 2023-12-13 09:54
- What version of macOS do you use? (I observed this problem on Sonoma, so I'm curious whether we had this problem on Ventura)
- Do you observe the problem when switching between h_tiles and v_tiles layouts? (I'm curious whether the problem happens only when AeroSpace moves the windows at the bottom right corner, or whether it happens generally when it resizes/moves windows)
  - If the answer is yes. Do you observe the same problem in Amethyst/yabai when changing layout/moving windows? 
- Did you try to reboot?
- Reduced motion doesn't cause this problem on my machine

**Comment by MatthiasGrandl** [comment] 2023-12-13 09:59
> What version of macOS do you use? (I observed this problem on Sonoma, so I'm curious whether we had this problem on Ventura)

Jup Sonoma 17.2

> Do you observe the problem when switching between h_tiles and v_tiles layouts? (I'm curious whether the problem happens only when AeroSpace moves the windows at the bottom right corner, or whether it happens generally when it resizes/moves windows)

Yes, the affected window is animated in this case as well.

> If the answer is yes. Do you observe the same problem in Amethyst/yabai when changing layout/moving windows?

Haven't tried.

> Did you try to reboot?

jup, still comes back


> I noticed this with specific windows. For me this never happens for any app except Firefox, Firefox animates every time (when moving window and when switching to a workspace with Firefox)

90% of the time this happens for me on Firefox as well. I have seen iTerm2 and Discord show this behavior as well though.

**Comment by MatthiasGrandl** [comment] 2023-12-13 10:07
> If the answer is yes. Do you observe the same problem in Amethyst/yabai when changing layout/moving windows?

I just tried the window management in Raycast as that's what I already had installed. When moving the affected Firefox window with Raycast, I don't get any animation.

Here is what I did:
1. Made sure the behavior was present on Firefox before disabling AeroSpace
2. Used Raycast to resize Firefox -> observed no animation
3. Reenabled AeroSpace and behavior again is present on Firefox.

**Comment by nikitabobko** [comment] 2023-12-13 10:33
I'm genuinely surprised to see that there are no similar issues in Amethyst tracker https://github.com/ianyh/Amethyst/issues?q=is%3Aissue+animation (neither I don't remember that being mentioned in any of their docs/settings)

Neither I was able to find anything similar in yabai tracker https://github.com/koekeishiya/yabai/issues?page=1&q=is%3Aissue+animation (but there are 100+ issues, I could easily miss it)

Now, I'm curious to check whether unwanted animations happen in yabai/Amethyst/Raycast when _bad accessibility options_ are enabled (_bad accessibility options_ are options that are known to cause unwanted animations in AeroSpace). I will be able to check it later this evening

If there are still no animations in Amethyst/yabai then it might mean that they use accessibility API in a different manner

> 1. Made sure the behavior was present on Firefox before disabling AeroSpace
> 2. Used Raycast to resize Firefox -> observed no animation
> 3. Reenabled AeroSpace and behavior again is present on Firefox.

That's interesting, thanks for sharing. Potentially, it could also mean that Raycast uses accessibility API in some different manner (same as Amethyst/yabai)

**Comment by koihia** [comment] 2023-12-14 11:13
Rectangle used to have a [similar issue](https://github.com/rxhanson/Rectangle/issues/165).

**Comment by MatthiasGrandl** [comment] 2023-12-15 08:44
@nikitabobko I'd happily put up a $50 bug bounty for this. Other than this little bug, AeroSpace works perfectly for me and I'd be happy to financially contribute!

**Comment by nikitabobko** [comment] 2023-12-18 00:42
Should be fixed in 0.7.1-Beta. Please let me know if it's fixed

**Comment by MatthiasGrandl** [comment] 2023-12-18 01:40
@nikitabobko seems to have fixed it! haven't tested for very long, but previously affected windows now work after update. Let me know how I can pay my promised bounty :)

On an unrelated note, I couldn't update via homebrew, it would just try to reinstall 0.6.2-Beta. Not sure if I did something wrong or if something is wrong with the cask. Had to update manually.

**Comment by koihia** [comment] 2023-12-18 03:42
@nikitabobko Thank you! It seems that the issue has been fixed for me.

@MatthiasGrandl make sure to run `brew update` before executing `brew upgrade`.

**Comment by MatthiasGrandl** [comment] 2023-12-18 07:17
> make sure to run brew update before executing brew upgrade.

🤦 obviously that's it... thanks!

**Comment by nikitabobko** [comment] 2023-12-19 00:15
> Let me know how I can pay my promised bounty :)

@MatthiasGrandl I appreciate that you want to financially contribute, thank you! You're not the first person to express a willingness to offer financial support for the project.

But money is a complicated matter. I haven't figured out whether I want to get paid for the AeroSpace. Money means obligations (or might be considered as such by some people), and I don't want to get obligated.

If at some point I see that AeroSpace takes more time than I want to then I will consider financing.

Thank you

**Comment by nikitabobko** [comment] 2023-12-19 00:15
I'm closing this issue since it's fixed. Feel free to comment or open a new issue if you find problems

**Closed by nikitabobko** 2023-12-19 00:15 UTC

**Comment by MatthiasGrandl** [comment] 2023-12-19 10:47
> But money is a complicated matter. I haven't figured out whether I want to get paid for the AeroSpace. Money means obligations (or might be considered as such by some people), and I don't want to get obligated.

Totally get it. I guess bounties can be thought of a bit different. They are one of payments for specific milestones. Beyond that there shouldn't be any obligation. But if you are not comfortable taking financial contributions I will respect that decision!

**Comment by MatthiasGrandl** [comment] 2024-03-15 09:31
This behavior seems to be back in recent versions. Firefox appears to be the only app affected though.

**Comment by nikitabobko** [comment] 2024-03-15 21:12
Sad to hear it, because I didn't touch anything around [`disableAnimations`](https://github.com/nikitabobko/AeroSpace/commit/12e7737a9eda1fffb3cfc883c383fef4f463861e) since than

The situation hasn't changed on my machine, I still cannot reproduce it, even Firefox isn't animated.

Even if I enable accessibility features that are known to cause animations (such as "Full Keyboard Access"), the animations don't happen on my machine. The hack with `disableAnimations` still successfully blocks the animations on my machine

Have you tried checking the trivial stuff: reboot?

Alternatively, if you know the version that you've upgraded from, you can `git bisect` the repo, to find the commit that caused this problem
