### ISSUE TITLE
AeroSpace Runtime Error

### ISSUE THREAD

**Issue by DonCappuccin0** [nikitabobko/AeroSpace#806] opened 2024-12-04 06:34 UTC
I opened my mac this morning and got this issue pop up : 
```
##### AeroSpace Runtime Error #####

Please report to:
    https://github.com/nikitabobko/AeroSpace/issues/new
    Please describe what you did to trigger this error

Message: Window(title: 'Optional("Proton VPN")', role: 'Optional("AXWindow")', subrole: 'Optional("AXDialog")', identifier: 'nil', modal: 'Optional("false")', windowId: 'Optional("15674")') is already unbound
Version: 0.16.0-Beta
Git hash: d172dfd8a92f2d339f3d46a12a297e43e80768ca
Coordinate: /Users/bobko/a/AeroSpace/Sources/AppBundle/tree/TreeNode.swift:115:34 unbindFromParent()
recursionDetectorDuringFailure: false
cli: false

Stacktrace:
0   AeroSpace                           0x00000001026c3648 $s6Common6errorT_4file4line6column8functionxSS_SSS2iSStlF + 740
1   AeroSpace                           0x0000000102573324 $s9AppBundle33restoreClosedWindowsCacheIfNeeded19newlyDetectedWindowSbAA0K0C_tF + 2548
2   AeroSpace                           0x0000000102560c28 $s9AppBundle9MacWindowC3get3app02axD07startupACSgAA0cA0C_So14AXUIElementRefaSbtFZTf4nnnd_n + 1648
3   AeroSpace                           0x000000010255cfa0 $sSTsE10compactMapySayqd__Gqd__Sg7ElementQzKXEKlFSaySo14AXUIElementRefaG_9AppBundle6WindowCTg503$s9f55Bundle03MacA0C25detectNewWindowsAndGetAll7startupSayAA6h15CGSb_tFAGSgSo14D9RefaXEfU_AI0kF0CSbTf1cn_nTf4ngn_n + 248
4   AeroSpace                           0x00000001025557ac $s9AppBundle03MacA0C25detectNewWindowsAndGetAll7startupSayAA6WindowCGSb_tF + 256
5   AeroSpace                           0x00000001025455d0 $s9AppBundle41detectNewWindowsAndAttachThemToWorkspaces33_9D4CAE07A16011BB7304F8F5007BD739LL7startupySb_tF + 384
6   AeroSpace                           0x00000001025429c4 $s9AppBundle14refreshSession26screenIsDefinitelyUnlocked7startup10forceFocus4bodyxSb_S2bxyXEtlFyt_Tg503$s9A70Bundle9MacWindowC14garbageCollect22skipClosedWindowsCacheySb_tFyyXEfU_SSTf1nnnnc_n + 752
7   AeroSpace                           0x000000010255d410 $s9AppBundle9MacWindowC14garbageCollect22skipClosedWindowsCacheySb_tF + 712
8   AeroSpace                           0x00000001025479f8 $s9AppBundle9gcWindowsyyF + 500
9   AeroSpace                           0x0000000102542968 $s9AppBundle14refreshSession26screenIsDefinitelyUnlocked7startup10forceFocus4bodyxSb_S2bxyXEtlFyt_Tg503$s9A70Bundle9MacWindowC14garbageCollect22skipClosedWindowsCacheySb_tFyyXEfU_SSTf1nnnnc_n + 660
10  AeroSpace                           0x000000010255d410 $s9AppBundle9MacWindowC14garbageCollect22skipClosedWindowsCacheySb_tF + 712
11  AeroSpace                           0x00000001025479f8 $s9AppBundle9gcWindowsyyF + 500
12  AeroSpace                           0x0000000102542ed4 $s9AppBundle14refreshSession26screenIsDefinitelyUnlocked7startup10forceFocus4bodyxSb_S2bxyXEtlFyt_Tg503$s9a32Bundle16refreshAndLayout26screenfG31Unlocked7startupySb_SbtFyyXEfU_Tf1nnnnc_n + 644
13  AeroSpace                           0x00000001024e7824 $s9AppBundle14GlobalObserverC7onNotif33_F1205CFDC13498282252A689C79131F6LLyy10Foundation12NotificationVFZTf4nd_n + 384
14  AeroSpace                           0x00000001024e6b08 $s10Foundation12NotificationVIeghn_So14NSNotificationCIeyBhy_TR + 116
15  CoreFoundation                      0x00000001896427ec __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 128
16  CoreFoundation                      0x00000001896d366c ___CFXRegistrationPost_block_invoke + 88
17  CoreFoundation                      0x00000001896d35b4 _CFXRegistrationPost + 436
18  CoreFoundation                      0x000000018961143c _CFXNotificationPost + 732
19  Foundation                          0x000000018a7b9b14 -[NSNotificationCenter postNotificationName:object:userInfo:] + 88
20  AppKit                              0x000000018d311668 applicationStatusSubsystemCallback + 728
21  LaunchServices                      0x0000000189ae7e84 ___LSScheduleNotificationFunction_block_invoke_2 + 52
22  CoreFoundation                      0x000000018964d8c0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 28
23  CoreFoundation                      0x000000018964d7d0 __CFRunLoopDoBlocks + 356
24  CoreFoundation                      0x000000018964cc00 __CFRunLoopRun + 2432
25  CoreFoundation                      0x000000018964bbc4 CFRunLoopRunSpecific + 588
26  HIToolbox                           0x0000000194abbf64 RunCurrentEventLoopInMode + 292
27  HIToolbox                           0x0000000194ac1d54 ReceiveNextEventCommon + 636
28  HIToolbox                           0x0000000194ac1eb8 _BlockUntilNextEventMatchingListInModeWithFilter + 76
29  AppKit                              0x000000018d177a08 _DPSNextEvent + 660
30  AppKit                              0x000000018dab7e0c -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 688
31  AppKit                              0x000000018d16aae0 -[NSApplication run] + 480
32  AppKit                              0x000000018d141364 NSApplicationMain + 888
33  SwiftUI                             0x00000001b77f1340 $s7SwiftUI6runAppys5NeverOSo21NSApplicationDelegate_So11NSResponderCXcFTf4e_nAA07TestingdG0C_Tg5Tm + 160
34  SwiftUI                             0x00000001b7c61ee4 $s7SwiftUI6runAppys5NeverOxAA0D0RzlF + 84
35  SwiftUI                             0x00000001b7fdaf24 $s7SwiftUI3AppPAAE4mainyyFZ + 224
36  AeroSpace                           0x00000001024e53ec main + 36
37  dyld                                0x00000001891e4274 start + 2840
```

**Comment by nikitabobko** [comment] 2024-12-04 10:08
Duplicate of https://github.com/nikitabobko/AeroSpace/issues/771

**Closed by nikitabobko** 2024-12-04 10:08 UTC
Labels: duplicate
