### ISSUE TITLE
Wrong monitors order compared to other tools like sketchybar

### ISSUE THREAD

**Issue by tobiasgiese** [nikitabobko/AeroSpace#336] opened 2024-07-22 08:45 UTC
AeroSpace is using a *custom* order for the monitors.

https://github.com/nikitabobko/AeroSpace/blob/b0ed972dd26d37dc0552d2865bf7de56f8c0d388/Sources/AppBundle/model/Monitor.swift#L82-L84

Other tools like Sketchybar are using a different order. The first monitor is **always** the primary monitor.
AeroSpaces first monitor is always the most left monitor, regardless if it's the primary monitor or not.

This makes it pretty hard to use `aerospace list-workspaces` and `aerospace --add event [...] display=$monitorID` for instance.

In my case I have the Macbook on the left side of the monitor -- where my external monitor is primary.
Running the following command will add all workspaces to the wrong monitor:

```bash
for monitorID in $(aerospace list-monitors | awk '{print $1}'); do
    for sid in $(aerospace list-workspaces --monitor $monitorID); do
        sketchybar --add item \
            space.$sid left \
            display=$monitorID
            # [...] and some more parameters
    done
done
```

<details>

  <summary>Snippet to reproduce</summary>

```bash
for monitorID in $(aerospace list-monitors | awk '{print $1}'); do
    sketchybar --add item find.mon.$monitorID left \
        --set find.mon.$monitorID \
        icon="$monitorID" \
        display=$monitorID
done
```

</details>

IMO it is worth the effort to give the users the ability to adjust the order. Something like an additional command parameter to select if it will be ordered align to the X and Y axis or if we want to have the primary monitor always as the first one.

**Comment by nikitabobko** [comment] 2024-07-22 10:53
> Other tools like Sketchybar are using a different order. The first monitor is always the primary monitor.

What is the order of the remaining monitors?

**Comment by apoxa** [comment] 2024-07-22 12:21
I can reproduce this issue. 
When using 3 monitors, the order in `aerospace list-monitors` is from left to right as arranged in the Display section of *System Settings.app*. <img width="597" alt="image" src="https://github.com/user-attachments/assets/1ab11dad-0b27-43bd-a890-34b64a8807ea">

When 2 monitors are on top of each other the order is from top to bottom, left to right:
<img width="598" alt="image" src="https://github.com/user-attachments/assets/0fe3fe42-e826-4660-90ae-dc11f0b2c1e6">

This is a bit unexpected, because what's numbered 3 is my main display, where the other 2 are configured as extended displays.

**Comment by tobiasgiese** [comment] 2024-07-22 12:33
Easy snippet to reproduce the issue, put this somewhere in your `sketchybarrc` (maybe before your aersoapce stuff):

```bash
for monitorID in $(aerospace list-monitors | awk '{print $1}'); do
    sketchybar --add item find.mon.$monitorID left \
        --set find.mon.$monitorID \
        icon="$monitorID" \
        display=$monitorID
done
```

**Comment by apoxa** [comment] 2024-07-22 12:37
Thanks for the snippet! Here's the order from my first arrangement:

| Aerospace | Sketchybar |
|--------|--------|
| 1 | 3 |
| 2 | 2 |
| 3 | 1 | 

In the second arrangment it's ordered another way:

| Aerospace | Sketchybar |
|--------|--------|
| 1 | 2 |
| 2 | no ID shown |
| 3 | 1 |

**Comment by tobiasgiese** [comment] 2024-07-25 14:14
Just FYI, wrote a small bash script to fix the order for sketchybar:

```bash
monitors=$(aerospace list-monitors)
monitorsSorted=("$(echo "$monitors" | grep "LG HDR WQHD+")")
monitorsSorted+=("$(echo "$monitors" | grep -v "LG HDR WQHD+")")

printf '%s\n' "${monitorsSorted[@]}" | sed "$1,1!d" | awk '{print $1}'
```

**Comment by tobiasgiese** [comment] 2024-07-28 11:33
@nikitabobko with the most recent beta version v0.13.1-beta the monitor list is broken (at least for me).

```
❯ aerospace list-monitors
0 | Built-in Retina Display
❯ aerospace list-workspaces --monitor 0
Invalid monitor ID: 0
❯ aerospace list-workspaces --monitor 1
1
2
3
4
5
6
7
8
9
10
```

**Comment by nikitabobko** [comment] 2024-07-28 18:02
@tobiasgiese Thanks for reporting! Should be fixed in 0.13.2

**Comment by ggalves** [comment] 2024-10-13 19:45
I'm with this issue too.

I don't know if there is any special reason for Aerospace don't use `displayID` as index for monitors. But, although I'm not sure, I guess giving the variable `%{display-id}` as an option for formatting the output of `aerospace list-monitors` would be enough to solve the integration with sketchybar and probably other tools. I mean, Aerospace can keep its method of indexing monitors, while you can use `aerospace list-monitors --format '%{monitor-id} -> %{display-id}'` to do the mapping.

I'm not sure if sketchybar is using displayId as ids for the displays though, but I think at least it should

**Comment by pszypowicz** [comment] 2024-10-14 19:02
just FYI - developer of sketchybar responded with an information how monitors are indexed there: https://github.com/FelixKratz/SketchyBar/issues/628#issuecomment-2407439225

**Comment by nikitabobko** [comment] 2024-10-14 20:11
> I don't know if there is any special reason for Aerospace don't use displayID as index for monitors

@ggalves can you please point out to the specific `displayID` API? AeroSpace uses [`NSScreen` API](https://developer.apple.com/documentation/appkit/nsscreen). And I don't anything about displayID in `NSScreen` docs

AeroSpace uses own indexing method because:
1. Apple API/docs don't say anything about order
2. It's just logical to order monitors from left to right, top to bottom (AeroSpace sorts by `minX` and for every monitors with equal `minX` it sorts by `minY`). The same order is reflected in AeroSpace menu bar.

> developer of sketchybar responded with an information how monitors are indexed there

Thanks for the info! AFAIK, `SLSCopyManagedDisplays` is a private API in SkyLight private framework. And AeroSpace won't be using this API because of that.

Nevertheless, the order of monitors that people describe in this issue looks similar to what [NSScreen.screens](https://developer.apple.com/documentation/appkit/nsscreen/1388393-screens) returns (main monitor goes first, all others go next enumerated from left to right). The docs only specify what is the first element of the array, so it's actually undefined in what order all others monitors go.

I don't mind introducing `%{display-id}` in `--format` options as @ggalves suggests (though, I'd call it smth like `%{macos-native-monitor-id}` or `%{nsscreen-screens-monitor-id}`), but I'd like to first hear from @ggalves about the `displayID` API he was talking about

And one last question: does sketchybar use 1-based or 0-based indices?

**Comment by ggalves** [comment] 2024-10-14 20:25
@nikitabobko I'm not an Apple developer neither know the MacOS API, but I was yesterday messing around with `pyobjc` in python. Looks like this reference may help: 

- From https://developer.apple.com/documentation/appkit/nsscreen/1388360-devicedescription#discussion
> To access this value, specify the Objective-C string @"NSScreenNumber" as the key when requesting the item from the dictionary. The value associated with this key is an [NSNumber](https://developer.apple.com/documentation/foundation/nsnumber) object containing the display ID value.

@pszypowicz Do you know if `SLSCopyManagedDisplays` returns in the same order?

> And one last question: does sketchybar use 1-based or 0-based indices?

In my tests seems to be 1-based

**Comment by ggalves** [comment] 2024-10-14 20:58
Answering myself

> Do you know if SLSCopyManagedDisplays returns ordered by this displayID?

I tested it and it seems to be 3 different orders (aerospace, sketchybar and these ids provided by the NSScreen API)... So, at least for the integration of Aerospace with SketchyBar, I don't think it will be possible without having a script that translates one logic to the other 😞

**Comment by nikitabobko** [comment] 2024-10-14 21:04
Yeah, I was typing the same thing.

I have 3 monitors ordered along x-axis from left to right: Built-in Retina Display, DELL U2723QE, DeskPad Display. AeroSpace predictably uses plain left to right order:
```
1 | Built-in Retina Display
2 | DELL U2723QE
3 | DeskPad Display
```

But the following code:
```
print(NSScreen.screens.enumerated()
    .map {
        (
            "Apple NSScreenNumber API: \($0.element.deviceDescription[NSDeviceDescriptionKey("NSScreenNumber")] as! CGDirectDisplayID)",
            "NSScreen.screens index: \($0.offset + 1)",
            $0.element.localizedName
        )
    }
)
```
prints the following (I wrapped elements of the array on new lines for easier readability):
```
[
    ("Apple NSScreenNumber API: 2", "NSScreen.screens index: 1", "DELL U2723QE"),
    ("Apple NSScreenNumber API: 1", "NSScreen.screens index: 2", "Built-in Retina Display"),
    ("Apple NSScreenNumber API: 7", "NSScreen.screens index: 3", "DeskPad Display")
]
```

The Apple documented `NSScreenNumber` simply doesn't make sense.

**Comment by nikitabobko** [comment] 2024-10-14 21:41
The following commit implements `%{monitor-appkit-nsscreen-screens-id}` https://github.com/nikitabobko/AeroSpace/commit/125e9b94040e95204c6a05cd5089022ba92efbce which so far looks identical to the private API that sketchybar uses. But nobody guaranteed that, and nobody guarantees that sketchybar order (that uses private `SLSCopyManagedDisplays` API) will remain the same as `%{monitor-appkit-nsscreen-screens-id}` (which uses public `NSScreen.screens`, but order is undocumented by Apple)

If you want stronger guarantees please reach out to sketchybar developer for a feature request to expose/interpret monitor IDs accessible via public API or at least predictably stable order. For example, AeroSpace uses its own predictably stable order by sorting by `minX` and then `minY` https://github.com/nikitabobko/AeroSpace/blob/898331e79086bd7f56fc4588308bc3819587a320/Sources/AppBundle/model/Monitor.swift#L83 Point (0, 0) is the top left corner of the main monitor, x-axis points to the right, y-axis points down. Or, as it was mentioned, `deviceDescription[NSDeviceDescriptionKey("NSScreenNumber")]` is also a good alternative (the returned number is funky, but at least it's documented)

I will close this issue when the commit is released

**Comment by ggalves** [comment] 2024-10-14 22:01
@nikitabobko `NSScreenNumber` isn't even sequential? that's wild 💀 . I can see now why Aerospace use it's own method, it is indeed the most consistent.

> which so far looks identical to the private API that sketchybar uses

The NSScreen also puts the main monitor as first? If not, I would advise that sketchybar does it as reported earlier in this issue. Just mentioning it because you've mentioned the sketchybar in the docs in this commit

> If you want stronger guarantees please reach out to sketchybar developer for a feature request to expose/interpret monitor IDs accessible via public API or at least predictably stable order

Seems fair enough and I agree with the decision

> Or, as it was mentioned, deviceDescription[NSDeviceDescriptionKey("NSScreenNumber")] is also a good alternative (the returned number is funky, but at least it's documented)

Was it also implemented in this Aerospace by this commit? I couldn't find a reference

---

Thank you so much for effort and sorry if I gave any misleading information from `displayID`, I was just exploring things trying to find some common value that could be used as an anchor between different tools. 😄

**Comment by pszypowicz** [comment] 2024-10-15 07:14
> And one last question: does sketchybar use 1-based or 0-based indices?

In my tests: displays goes from 1. I use display=0 to hide stuff (icons/spaces). 

My actual workaround is to set far left monitor as "main".

**Comment by nikitabobko** [comment] 2024-10-15 08:40
> The NSScreen also puts the main monitor as first?

Yes, it does

> Was it also implemented in this Aerospace by this commit? 

No, it wasn't implemented, because there is no motivation to do that (sketchybar uses different indexing method anyway). If in future, motivation appears, it can easily be added

**Comment by nikitabobko** [comment] 2024-11-27 23:52
Released in 0.16.0-Beta

**Closed by nikitabobko** 2024-11-27 23:52 UTC
Labels: problem, triaged

**Comment by dibi-codes** [comment] 2025-02-10 14:01
This isn't working for me and I'm a little bit confused..

The aerospace query lists the following:
```
$ aerospace list-monitors --format '%{monitor-id} %{monitor-appkit-nsscreen-screens-id}'
1 3
2 1
3 2
```

Sketchybar query result:

```sketchybar --query displays
[
	{
		"arrangement-id":1,
		"DirectDisplayID":3,
		"UUID":"BEDCE7AF-C20D-4954-BBEB-B2A2BDD4E93B",
		"frame":{
		"x":0.0000,
		"y":0.0000,
		"w":3360.0000,
		"h":1890.0000
		}
	},
	{
		"arrangement-id":2,
		"DirectDisplayID":2,
		"UUID":"80485376-933C-42DA-BF88-DD6AB6318E37",
		"frame":{
		"x":-1200.0000,
		"y":42.0000,
		"w":1200.0000,
		"h":1920.0000
		}
	},
	{
		"arrangement-id":3,
		"DirectDisplayID":1,
		"UUID":"37D8832A-2D66-02CA-B9F7-8F30A301B230",
		"frame":{
		"x":746.0000,
		"y":1890.0000,
		"w":2056.0000,
		"h":1329.0000
		}
	}
]
```

My problem is that arrangement-id: 2 (DirectDisplayID: 2) is aerospace monitor id 1 

Is this a problem within sketchybar, aerospace or even my arrangement?

![](https://ds.dibi.dev/d/X20PYUZoQJi9.png)

**Comment by So-Cool** [comment] 2025-08-22 11:37
If anyone is still looking for a reliable solution to map `%{monitor-appkit-nsscreen-screens-id}` from AeroSpace to the display ID used by SketchyBar, I got this:
```bash
displayMap=$(swift -e '
  import Cocoa
  var displayMap : [Int: UInt32] = [:]
  for (nsscreenid, screen) in NSScreen.screens.enumerated() {
      if let directdisplayid = screen.deviceDescription[NSDeviceDescriptionKey("NSScreenNumber")] as? UInt32 {
          displayMap[nsscreenid+1] = directdisplayid
      }
  }
  let jsonCompatibleDict = Dictionary(uniqueKeysWithValues:
      displayMap.map { (key, value) in (String(key), value) }
  )

  if let jsonData = try? JSONSerialization.data(withJSONObject: jsonCompatibleDict, options: .prettyPrinted),
     let jsonString = String(data: jsonData, encoding: .utf8) {
      print(jsonString)
  }')
sketchyDisplays=$(sketchybar --query displays)

nsscreen=2

# Get DirectDisplayID for our NSScreenID
ddid=$(echo $displayMap | jq --arg nsscreen "$nsscreen" -r '.[$nsscreen]')
# Extract the display ID used by SketchyBar from DirectDisplayID
sdid=$(echo $sketchyDisplays | jq --argjson ddid "$ddid" '.[] | select(.DirectDisplayID == $ddid) | ."arrangement-id"')
```
Then you can set `display="$sdid"` when constructing an element for your SketchyBar.
