### ISSUE TITLE
Possibility to use only the right option or the left option command.

### ISSUE THREAD

**Issue by Gabulhas** [nikitabobko/AeroSpace#326] opened 2024-07-10 16:32 UTC
I'm using a MacBook Air with a Portuguese keyboard.

Given that I'm using the workspaces from 0 to 9, I can't type multiple characters on my keyboard, like [ { ] } @, because in order to type those I have to hit the same keys that I use to switch workspaces or send windows to other workspaces.

**Comment by nikitabobko** [comment] 2024-07-16 20:13
Duplicate of #28

**Closed by nikitabobko** 2024-07-16 20:13 UTC
