### ISSUE TITLE
MacOS Sequoia 15.0 Compatibility

### ISSUE THREAD

**Issue by kaiwalyajoshi** [nikitabobko/AeroSpace#514] opened 2024-09-16 17:36 UTC
MacOS Sequoia was released [today](https://www.apple.com/macos/macos-sequoia/), has anyone tried it out with Aerospace?

I'm holding off on the MacOS upgrades incase there are any bugs with Aerospace.

**Comment by sashaaldrick** [comment] 2024-09-16 19:29
I just upgraded without even thinking about Aerospace as I'm so used to it 😅 as far as I can tell everything works great.

**Comment by diogox** [comment] 2024-09-16 20:02
Can confirm, so far so good 🙌

**Comment by Alienover** [comment] 2024-09-17 04:15
Anyone used `alt + number` to focus workspace?
e.g.: 
```toml
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
# ...
```
I got those special characters no matter in kitty or mac built-in terminal.
<img width="401" alt="image" src="https://github.com/user-attachments/assets/09d609d5-3dd7-4a5b-96a8-aeb481d23ca4">

But outside the terminal app, it works well as before.

**Comment by lampewebdev** [comment] 2024-09-17 06:37
for me super + [anything] stopped working and shift + super + [anything] also stopped working. So I can not move around anything to a new workspace in aerospace

**Comment by sashaaldrick** [comment] 2024-09-17 07:59
> Anyone used `alt + number` to focus workspace? e.g.:
> 
> ```toml
> alt-1 = 'workspace 1'
> alt-2 = 'workspace 2'
> alt-3 = 'workspace 3'
> # ...
> ```
> 
> I got those special characters no matter in kitty or mac built-in terminal. <img alt="image" width="401" src="https://private-user-images.githubusercontent.com/12182069/368003311-09d609d5-3dd7-4a5b-96a8-aeb481d23ca4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NjAwMTksIm5iZiI6MTcyNjU1OTcxOSwicGF0aCI6Ii8xMjE4MjA2OS8zNjgwMDMzMTEtMDlkNjA5ZDUtM2RkNy00YTViLTk2YTgtYWViNDgxZDIzY2E0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDA3NTUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkMDM0MGEzNDlmZTIyNDU5ZGVhNDg1ZjJjNWUwY2FlMWIwOGQ0ZDJjZWNhOTVlOWUwNTZkMjU2ZDExODFkMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v_qpOSK24VbrqDahBA8h5-c0LWIw7EzrFJstYoklh58">
> 
> But outside the terminal app, it works well as before.
> 
> FYI
> 
> ```
> macOS Sequoia:  Version 15.0 (24A335)
> 
> Aerospace Version:
>   aerospace CLI client version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
>   AeroSpace.app server version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
> ```

I use alt + number for workspaces and everything works on my end just as before. Same for shift + alt for sending a window to that workspace. 

Same exact builds for macOS and Aerospace:

```sh
sw_vers
ProductName:		macOS
ProductVersion:		15.0
BuildVersion:		24A335
```

```sh
aerospace --version
aerospace CLI client version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
AeroSpace.app server version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
```

**Comment by lampewebdev** [comment] 2024-09-17 08:02
> > Anyone used `alt + number` to focus workspace? e.g.:
> > ```toml
> > alt-1 = 'workspace 1'
> > alt-2 = 'workspace 2'
> > alt-3 = 'workspace 3'
> > # ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I got those special characters no matter in kitty or mac built-in terminal. <img alt="image" width="401" src="https://private-user-images.githubusercontent.com/12182069/368003311-09d609d5-3dd7-4a5b-96a8-aeb481d23ca4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NjAwMTksIm5iZiI6MTcyNjU1OTcxOSwicGF0aCI6Ii8xMjE4MjA2OS8zNjgwMDMzMTEtMDlkNjA5ZDUtM2RkNy00YTViLTk2YTgtYWViNDgxZDIzY2E0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDA3NTUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkMDM0MGEzNDlmZTIyNDU5ZGVhNDg1ZjJjNWUwY2FlMWIwOGQ0ZDJjZWNhOTVlOWUwNTZkMjU2ZDExODFkMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v_qpOSK24VbrqDahBA8h5-c0LWIw7EzrFJstYoklh58">
> > But outside the terminal app, it works well as before.
> > FYI
> > ```
> > macOS Sequoia:  Version 15.0 (24A335)
> > 
> > Aerospace Version:
> >   aerospace CLI client version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
> >   AeroSpace.app server version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
> > ```
> 
> I use alt + number for workspaces and everything works on my end just as before. Same for shift + alt for sending a window to that workspace.
> 
> Same exact builds for macOS and Aerospace:
> 
> ```shell
> sw_vers
> ProductName:		macOS
> ProductVersion:		15.0
> BuildVersion:		24A335
> ```
> 
> ```shell
> aerospace --version
> aerospace CLI client version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
> AeroSpace.app server version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
> ```

try to focus kitty terminal and then to do the shortcuts this is where it breaks for me also. If not then it is something in the kitty config.

**Comment by GreenRuslan** [comment] 2024-09-17 11:55
I have one issue that was not present on Sierra. 

I use the Arc browser as the default. Also, I use their feature, which opens new links in the so-called "small browser," which can be closed if you don't want to open this link in the main space. 

Steps to reproduce:
- open Arc browser in the space
- open any link in a small browser (I open links from the messenger which is float mode)
- close small browser

**Actual result**
The empty space that was occupied by the small browser stays, and the main browser window is not resized. The empty space after the small window is closed is still registered as a window, and I can switch to it. 

**Expected result**
The small browser is closed, and the main browser window is resized.

**Comment by GreenRuslan** [comment] 2024-09-17 11:58
Adding info to my previous message - when it happens, It stops going to the messenger window, which is in float mode. I can jump only to the empty space, which stays after the small browser window is closed and the main window. When I restart the browser - everything works as it should.

**Comment by aaftre** [comment] 2024-09-17 18:36
i'm having issues on sequoia with aerospace resizing existing windows after a window on a desktop is closed. similar to @GreenRuslan's post. also using arc, but other apps might be affected as well.

**Comment by Jihillestad** [comment] 2024-09-17 20:13
Small issue here, some strange artifact in the lower right corner of the monitor:

![image](https://github.com/user-attachments/assets/43b387ec-37e4-438b-bf89-73a3f58fd1aa)

**Comment by ezhang7423** [comment] 2024-09-17 20:55
I am getting the same error as @GreenRuslan and @aaftre . When I close a window, the remaining windows don't take up the empty space. As a result, I have a whole host of empty space which grows larger with each window that close.

**Comment by kaiwalyajoshi** [comment] 2024-09-17 21:51
> Small issue here, some strange artifact in the lower right corner of the monitor:
> 
> ![image](https://private-user-images.githubusercontent.com/64490910/368326133-43b387ec-37e4-438b-bf89-73a3f58fd1aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MTAwMTEsIm5iZiI6MTcyNjYwOTcxMSwicGF0aCI6Ii82NDQ5MDkxMC8zNjgzMjYxMzMtNDNiMzg3ZWMtMzdlNC00MzhiLWJmODktNzNhM2Y1OGZkMWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDIxNDgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0OWZmODBhYzBmMTQxYzcwZTY1YTJkZWJmYzMwMzM3MjEzM2JhYWUwZDBjNTAyMDRjMmRkYTQ2N2NiNTdjYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pHb5tC1MrXlCVGG9rqTyAEOzfYkFTf1B7VlMCFMpHzA)

@Jihillestad 
Are you running on multiple monitors? There's a [monitor arrangement guide here](https://nikitabobko.github.io/AeroSpace/guide#proper-monitor-arrangement).

**Comment by nickdoherty** [comment] 2024-09-18 01:47
I have the same issue as @Jihillestad. Single monitor, multiple spaces.

**Comment by junereycasuga** [comment] 2024-09-18 03:10
mine had no issues. focusing to other window from kitty had no problems as well.

```
ProductName:            macOS
ProductVersion:         15.0
BuildVersion:           24A335

aerospace CLI client version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
AeroSpace.app server version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
```

**Comment by jalet** [comment] 2024-09-18 07:10
Had no issues as well

```console
15.0 (24A335)

aerospace CLI client version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
AeroSpace.app server version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
```

**Comment by Jihillestad** [comment] 2024-09-18 07:39
> > Small issue here, some strange artifact in the lower right corner of the monitor:
> > ![image](https://private-user-images.githubusercontent.com/64490910/368326133-43b387ec-37e4-438b-bf89-73a3f58fd1aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MTAwMTEsIm5iZiI6MTcyNjYwOTcxMSwicGF0aCI6Ii82NDQ5MDkxMC8zNjgzMjYxMzMtNDNiMzg3ZWMtMzdlNC00MzhiLWJmODktNzNhM2Y1OGZkMWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDIxNDgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0OWZmODBhYzBmMTQxYzcwZTY1YTJkZWJmYzMwMzM3MjEzM2JhYWUwZDBjNTAyMDRjMmRkYTQ2N2NiNTdjYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pHb5tC1MrXlCVGG9rqTyAEOzfYkFTf1B7VlMCFMpHzA)
> 
> @Jihillestad Are you running on multiple monitors? There's a [monitor arrangement guide here](https://nikitabobko.github.io/AeroSpace/guide#proper-monitor-arrangement).

It occurs on single and multiple monitors

**Comment by tuzemec** [comment] 2024-09-18 13:58
This is interesting: https://github.com/p0deje/Maccy/issues/872
It seems that Apple is kinda restricting global shortcuts with only <kbd>option</kbd> as a modifier in Sequoia.
And by "interesting" I mean "wtf"?

Can anyone confirm this?

**Comment by tkivela** [comment] 2024-09-18 14:03
Option key shortcuts work with macOS 15.0 & Aerospace fine atleast for me.
But can confirm that there's is a bug with resizing (the one that [ezhang7423](https://github.com/ezhang7423) mentioned)

**Comment by shrimpram** [comment] 2024-09-18 15:28
Re: the close window/resizing issue that a few have mentioned, a workaround I've found is that using `aerospace close` ([see docs](https://nikitabobko.github.io/AeroSpace/commands#close)) to close a window ensures that the remaining windows are resized to take up any empty space. I've bound this to <kbd>alt + w</kbd> for convenience.

**Comment by mhesham32** [comment] 2024-09-18 16:39
I'm getting an issue for the tab I specified apps to launch on it. like the c tab chrome starts on it as a single window then I specify the profile to use. the opened profile window will use half of the screen despite that no other windows exist there if I closed this window and opened another app it will use third of the screen as if there are two other windows opened but that's not the case

**Comment by nikitabobko** [comment] 2024-09-18 17:07
> I am getting the same error as @GreenRuslan and @aaftre . When I close a window, the remaining windows don't take up the empty space. As a result, I have a whole host of empty space which grows larger with each window that close.

@GreenRuslan @aaftre @ezhang7423 please check if you have any other apps that use macOS accessibility API https://github.com/nikitabobko/AeroSpace/issues/471#issuecomment-2323256711 (System Settings -> Privacy & Security -> Accessibility)

**Comment by BasilPH** [comment] 2024-09-18 17:52
> @GreenRuslan @aaftre @ezhang7423 please check if you have any other apps that use macOS accessibility API [#471 (comment)](https://github.com/nikitabobko/AeroSpace/issues/471#issuecomment-2323256711) (System Settings -> Privacy & Security -> Accessibility)

I have the same issue, and I have a couple of apps that use macOS accessibility. Notably, I also use Contexts, which someone mentions in #471.

**Comment by aaftre** [comment] 2024-09-18 20:30
> > I am getting the same error as @GreenRuslan and @aaftre . When I close a window, the remaining windows don't take up the empty space. As a result, I have a whole host of empty space which grows larger with each window that close.
> 
> @GreenRuslan @aaftre @ezhang7423 please check if you have any other apps that use macOS accessibility API [#471 (comment)](https://github.com/nikitabobko/AeroSpace/issues/471#issuecomment-2323256711) (System Settings -> Privacy & Security -> Accessibility)

![image](https://github.com/user-attachments/assets/f5d83a7d-7dfa-4980-829c-421c99fcd6ee)

**Comment by johnnyBira** [comment] 2024-09-18 21:16
I updated to Sequoia today and installed AeroSpace for the first time.
For me almost non of the keybindings are working.

Also (and possible unrelated to the OS update) it seams like there are some kind of keybinding to the square and curly bracket keys. It's unclear to me what they are, since there is no sign of such a mapping in the config. I'm not able to output these keys (`[`, `]`, `{`, `}`) since they seam to be "blocked" and used by AeroSpace

**Comment by GreenRuslan** [comment] 2024-09-19 01:23
> > I am getting the same error as @GreenRuslan and @aaftre . When I close a window, the remaining windows don't take up the empty space. As a result, I have a whole host of empty space which grows larger with each window that close.
> 
> @GreenRuslan @aaftre @ezhang7423 please check if you have any other apps that use macOS accessibility API [#471 (comment)](https://github.com/nikitabobko/AeroSpace/issues/471#issuecomment-2323256711) (System Settings -> Privacy & Security -> Accessibility)

Here is the the list of apps:
![image](https://github.com/user-attachments/assets/bce70fa6-642e-4729-9129-0eb8b93ca942)

**Comment by ecosse3** [comment] 2024-09-19 15:35
I've updated to MacOS Sequoia 15.0 and Aerospace is pretty unusable now due to how it manages windows in virtual workspace. When I have one window only it still creates space for another and it seems broken. I need to use fullscreen for each app to be able to work with Aerospace.

Here is how I can move window by keybinding:
```
cmd-alt-shift-j = 'move down'
cmd-alt-shift-k = 'move up'
```
I'm using `layout tiles horizontal vertical`. `accordion` layout seems to work fine.

https://github.com/user-attachments/assets/b47aaaf0-4ff9-4828-91f6-9568bafba68d

**Comment by ezhang7423** [comment] 2024-09-20 00:11
@nikitabobko 
![Screenshot 2024-09-19 at 5 10 46 PM](https://github.com/user-attachments/assets/60c857c7-4f1f-4630-b2a2-aa1b17de71c7)

**Comment by ezhang7423** [comment] 2024-09-21 04:39
Do we have any updates on this?

**Comment by nikitabobko** [comment] 2024-09-21 12:15
I'm on Sequoia for the last few days and I see no regressions. Individual bugs must be reported as separate issues

The bug that some closed windows still take space is somehow related to using other apps like contexts app. I don't use contexts app, and I don't know what is the cause, other apps may also affect this (most probably they use accessibility api). But I think the fix suggested in this issue #445 will fix the bug.

> This is interesting: https://github.com/p0deje/Maccy/issues/872
It seems that Apple is kinda restricting global shortcuts with only option as a modifier in Sequoia.
And by "interesting" I mean "wtf?".

In macOS 15, Apple doesn't allow to capture hotkeys with `opt` and `opt+shift` modifier but it only affects sandboxed apps. AeroSpace is not a sandboxed, that's why it's not affected. AeroSpace needs to access accessibility API anyway, which is not available in sandbox. 

But it is sad to see Apple going in this directioon https://developer.apple.com/forums//thread/763878?src=push&answerId=804374022#804374022

**Closed by nikitabobko** 2024-09-21 12:15 UTC
Labels: question/discussion

**Comment by ianmartorell** [comment] 2024-09-24 16:50
@ezhang7423 I was experiencing the same issue with closed windows not being detected by Aerospace and after deactivating every other app in Accessibility under System Settings and rebooting, it hasn't happened again. From your list I see the ones we had in common are Raycast and skhd, although skhd I had already uninstalled. So I would suggest disabling Raycast (or everything) and rebooting to see if it that helps.

**Comment by Kikangh** [comment] 2024-09-24 18:11
Hi, if you don’t mind me asking, did you enable the applications after that in accessibility settings or not ?
I am not yet under sequoia, and won’t upgrade until I can « safely »  use all my applications, including Raycast and Aerospace, and I have quite a few applications needing accessibility setting enabled.

Le 24 sept. 2024 à 18:51, Ian Martorell ***@***.***> a écrit :


@ezhang7423 <https://github.com/ezhang7423> I was experiencing the same issue with closed windows not being detected by Aerospace and after deactivating every other app in Accessibility under System Settings and rebooting, it hasn't happened again. From your list I see the ones we had in common are Raycast and skhd, although skhd I had already uninstalled. So I would suggest disabling Raycast (or everything) and rebooting to see if it that helps.

**Comment by ianmartorell** [comment] 2024-09-24 18:53
> Hi, if you don’t mind me asking, did you enable the applications after that in accessibility settings or not ? I am not yet under sequoia, and won’t upgrade until I can « safely » use all my applications, including Raycast and Aerospace, and I have quite a few applications needing accessibility setting enabled. 

I've enabled back Logi Options+ and Raycast and no issues so far. Enabling Amazon Q did bring back the issue so I turned it back off, and I haven't felt like I'm missing anything else so far.

**Comment by ezhang7423** [comment] 2024-09-24 20:19
Unfortunately, disabling all my other applications in the Accessibility settings still did not fix the issue @ianmartorell . Would be extremely grateful @nikitabobko, as my workflow has been largely disrupted at this point.

**Comment by mhesham32** [comment] 2024-09-24 21:55
Thanks @ianmartorell AmazonQ was the issue for me as well after disabling its access I got Aerospace working as before

**Comment by Kikangh** [comment] 2024-09-25 05:25
Thanks Le 24 sept. 2024 à 20:53, Ian Martorell ***@***.***> a écrit :﻿

Hi, if you don’t mind me asking, did you enable the applications after that in accessibility settings or not ? I am not yet under sequoia, and won’t upgrade until I can « safely » use all my applications, including Raycast and Aerospace, and I have quite a few applications needing accessibility setting enabled.

I've enabled back Logi Options+ and Raycast and no issues so far. Enabling Amazon Q did bring back the issue so I turned it back off, and I haven't felt like I'm missing anything else so far.

**Comment by whkoh** [comment] 2024-09-26 00:44
Really tough to choose between contexts and aerospace. Are there any workarounds that still allow me to use contexts?

**Comment by aintyourcupoftea** [comment] 2024-10-03 23:06
Amazon Q is causing the issue for me. I uninstalled it and the issue was solved. But I wish to keep using Amazon Q!
I really wish this issue is fixed.
For now I am using @haveanicedavid workaround of adding alt-x='close' in my aerospace.toml but this way also it glitches sometimes.
I have also created a automator shell script :
`pkill -f AeroSpace
open -a "AeroSpace"`
and then assigned a keyboard shortcut for this script to run. Whenever I face this issue (which is like very often), I use the keyboard shortcut to restart aerospace and it starts working again.
But, it's my request to developers to please fix this issue! I will be really grateful.. thank you.
