### ISSUE TITLE
Feature Request: Add command to move node to workspace and monitor by window id

### ISSUE THREAD

**Issue by CheariX** [nikitabobko/AeroSpace#207] opened 2024-04-24 15:44 UTC
With 0.10.0, `focus` gained the `--window-id` property (#173).

Similarly, we need `--window-id` for the `move-node-to-workspace` command and probably, for the `move-node-to-monitor` command.

Currently, I would have to first `focus` the window in question and then move it to the desired workspace or monitor. Unfortunatly, focusing the window first lead to some undesired cluttering. Therefor, I propose to add the `--window-id` parameter to these commands. This would not only align these command's syntaxes, but it would also catch up with Yabai.

**Comment by nikitabobko** [comment] 2024-04-24 17:05
Duplicate of #186

**Closed by nikitabobko** 2024-04-24 17:05 UTC
