### ISSUE TITLE
Hiding applications leaves gaps

### ISSUE THREAD

**Issue by ullasholla** [nikitabobko/AeroSpace#36] opened 2023-12-04 21:29 UTC
I'm not sure if I missed something in the documentation. Hiding an application (Command+H) leaves a gap where the windows of that application were being displayed. Sometimes it can be hard to see what application was hidden when navigating to a different workspace at a later point in time.

For example, in this example I have hidden the Finder window and I see a gap between the two browser windows:
![Screenshot 2023-12-04 at 1 21 50 PM](https://github.com/nikitabobko/AeroSpace/assets/212316/f0eeb6f9-0759-45a8-bb43-24e6f1d4686d)

Any advice on how to deal with this?

Thank you!

**Comment by nikitabobko** [comment] 2023-12-04 21:44
Duplicate of #18

**Closed by nikitabobko** 2023-12-04 21:44 UTC

**Comment by nikitabobko** [comment] 2023-12-04 21:53
I answered you in #18
