### ISSUE TITLE
The fork.app git gui seems to break aerospace. every time you switch tabs the layout breaks

### ISSUE THREAD

**Issue by yspreen** [nikitabobko/AeroSpace#894] opened 2024-12-29 02:18 UTC
The fork.app git gui seems to break aerospace. every time you switch tabs the layout breaks. It's like a new empty window gets added to the layout, so say you have horizontal tiling enabled, the fork window gets squished to the right every time you switch tabs within the app

**Comment by nikitabobko** [comment] 2024-12-29 15:21
Most likely a duplicate of #68

**Closed by nikitabobko** 2024-12-29 15:21 UTC
Labels: bug
