### ISSUE TITLE
How to use with AZERTY keyboard?

### ISSUE THREAD

**Issue by Bubobubobubobubo** [nikitabobko/AeroSpace#273] opened 2024-06-12 09:27 UTC
Hi, I properly installed and configured Aerospace to my liking. It's working great, I have nothing to complain about. The problem I'm facing has to do with the keyboard layout I am using, AZERTY (PC) on MacOS. I am programming a lot, and many symbols are only accessible through the AltGr key, e.g. AltGr+5. I cannot use this key because it automatically switches to another space or performs another action.

Is it possible to differentiate between Alt and AltGr in the key mapping? This would solve the problem.

**Comment by nikitabobko** [comment] 2024-06-12 09:59
Duplicate of #28

**Closed by nikitabobko** 2024-06-12 09:59 UTC
