### ISSUE TITLE
WebStorm search window doesn't work with Aerospace

### ISSUE THREAD

**Issue by lajoskvcs** [nikitabobko/AeroSpace#694] opened 2024-11-12 13:05 UTC
**Describe the bug**
When I'm using aerospace the floating search window shows up only for a split second. The same goes for the command window or any jetbrains floating window.

My config is the default aerospace config.

In the video you can see:

- When I press shift+shift
- When I press cmd+shift+o
- When I click on the search button

https://github.com/user-attachments/assets/3c7cbcb8-f4d5-47fe-a500-60167999ad29

**Related issues you could find**
Please make sure to search for duplicates.
If you couldn't find the duplicates, linking related issues is helpful anyway.

**Comment by nikitabobko** [comment] 2024-11-14 09:21
Can't reproduce

Most probably a duplicate of #317

**Closed by nikitabobko** 2024-11-14 09:21 UTC
Labels: bug
