### ISSUE TITLE
[Feature request] Add the ability to assign custom names to workspaces

### ISSUE THREAD

**Issue by epszaw** [nikitabobko/AeroSpace#293] opened 2024-06-21 09:50 UTC
Hello!

Thank you for the outstanding project you did! Finally, I can use time manager in way I'm used to.

From my standpoint, the ability of workspace naming could be very useful because you can organize your work with a computer in a much more organic way. 

Let's imagine that you're used to using the first workspace for browser, the second one for personal things, the third for work-only applications, etc. In this case, you need to keep in mind, which workspace contains specific window, but in the case of named ones – you always see an assigned "domain".

**Comment by nikitabobko** [comment] 2024-06-21 10:19
Duplicate of #245

**Closed by nikitabobko** 2024-06-21 10:19 UTC
