### ISSUE TITLE
Feature: assign workspace to monitor

### ISSUE THREAD

**Issue by axelfahy** [nikitabobko/AeroSpace#14] opened 2023-11-09 13:50 UTC
I usually work with multiple monitors and like to know which workspace number is on which monitor. I tried moving them using `[move-workspace-to-display](https://github.com/nikitabobko/AeroSpace/blob/main/docs/commands.md#move-workspace-to-display)` but it's hard to end up with the correct workspace number on the wanted monitor. 

For example, on i3 I would set:  

```
# Location of workspaces 
workspace $ws1 output $monitorA
workspace $ws2 output $monitorA
workspace $ws3 output $monitorB
workspace $ws4 output $monitorB
```

Is it possible to assign workspaces to monitors?

**Comment by nikitabobko** [comment] 2023-11-09 14:07
> Is it possible to assign workspaces to monitors?

Not yet, but I agree that it needs to be supported

https://i3wm.org/docs/userguide.html#workspace_screen

I will eventually support it myself, but PRs are welcome. The entry points are 
- https://github.com/nikitabobko/AeroSpace/blob/main/src/tree/Workspace.swift#L126
- https://github.com/nikitabobko/AeroSpace/blob/main/src/tree/Workspace.swift#L92

**Comment by nikitabobko** [comment] 2023-11-10 11:21
The hardest part here is to design a syntax for the TOML config file.

Right now, I'm thinking about something like this:
```
[workspace-to-display-assignment]
workspace_name_1 = "ID_OF_THE_DISPLAY_1"
workspace_name_2 = "ID_OF_THE_DISPLAY_2"
```

But I'm not sure in what format `ID_OF_THE_DISPLAY_X` should be accepted. Probably all these possible values:
1. Display serial number
2. Name of the display in the settings. Like "DELL U2723QE"
3. "main" for the main display (the main display is configured in `System Settings`)
4. "secondary" for the cases when users have only two displays

**Comment by mike1808** [comment] 2023-11-14 19:16
I have an issue with having multiple monitors connected to a thunderbolt hub where one of those monitors is marked as "main". The problem is that the order of initialization of those monitors is not the same every time I plug the hub and sometimes my _main_ gets initialized after secondary which messes up with the ordering of workspace: sometimes the workspace X appears on the monitor 1 and sometimes on the monitor 2. 

Hopefully, being able to assign the workspace to a monitor will mitigate it.

**Closed** 2023-11-18 14:49 UTC

**Comment by nikitabobko** [comment] 2023-11-18 15:09
Fixed in 0.5.0-Beta

However, I have one deviation from the i3 model. workspace to monitor assignments is "forced" in AeroSpace. If you put the assignment in the config then `move-workspace-to-monitor` won't work for assigned workspaces

**Comment by axelfahy** [comment] 2023-11-19 14:43
Thanks a lot for this, I will try it this week!

**Comment by vitor-alves** [comment] 2023-11-19 22:04
@nikitabobko 
Thank you so much for implementing this feature. 
This was the only big struggle I had.
You're doing a great job with AeroSpace!

**Comment by techeddie** [comment] 2025-03-08 08:21
@nikitabobko
thank you very much as well.. making my live now easier on Mac
