### ISSUE TITLE
IntelliJ IDEs (IDEA/Goland etc) Search Everywhere / Code completion instantly disappears after opening

### ISSUE THREAD

**Issue by alexnguyennn** [nikitabobko/AeroSpace#168] opened 2024-02-20 12:41 UTC
## Background

Hi there,

I recently set up AeroSpace and have been mostly happy with it coming from issues with yabai and being an i3 user so first up, thanks for the great software - much appreciated. 
I've been able to work around most things missing except for an issue I'm experiencing with specific child windows inside IntelliJ IDEs (which seems surprising given that IDEA has been mentioned in other issues). 
I've seen the [existing floating window issue](https://github.com/nikitabobko/AeroSpace/issues/47#issuecomment-1858639795), however my problem seems slightly different (the settings window floats fine, for example) - my problem happens with 'Search Everywhere' and any code completion/intellisense popups. 
As soon as I open them, it feels like AeroSpace attempts to 'take control' of the windows, effectively closing them before I can do anything.

## Videos

I've tried to take some gifs to demonstrate the issue with AeroSpace enabled:
1. Showing my config (float everything)
![aerospace-demo-enabled-1](https://github.com/nikitabobko/AeroSpace/assets/12594234/c0bcecf0-cb86-4ebd-8240-a676f6cb8ad0)

2. Showing the instant disappearing windows
![aerospace-demo-enabled-2](https://github.com/nikitabobko/AeroSpace/assets/12594234/06c4c96f-0b94-4c27-9048-0deb24d9fc88)

3. Showing the expected behaviour that is restored when Aerospace is disabled again:
![aerospace-demo-disabled](https://github.com/nikitabobko/AeroSpace/assets/12594234/edfcc6c2-d4e9-4bf2-b1f6-314a54194a47)

## Accessibility app screenshots
I did take some screenshots with the accessibility app once Aerospace was disabled and the windows stayed open long enough. `aerospace debug-windows` didn't give me any output relevant to these windows (presumably because they close instantly; too fast for the watcher to pick up).

Search dialogs:
![2024-02-20_22-48](https://github.com/nikitabobko/AeroSpace/assets/12594234/ecdbc3cf-7cda-41e7-9a5b-ae866bb7b017)

![2024-02-20_22-47](https://github.com/nikitabobko/AeroSpace/assets/12594234/b4e04fcd-e9b8-41b5-9d6a-491f4e21895b)

Code completion:

![2024-02-20_22-49](https://github.com/nikitabobko/AeroSpace/assets/12594234/1e06ac83-c718-4f61-ba13-e78b55b6afb1)

## Other info
- AeroSpace version: v0.8.5-Beta d41205f
- macOS version: macos Ventura 13.6.4
- Your keyboard layouts (in case of global hotkeys handling problem): Use of hammerspoon/skhd for keybindings to focus windows directly to workaround `aerospace focus` not allowing us to focus specific windows yet.. but otherwise nothing fancy. Can provide configs if you think they'd be relevant.

## What have I tried?

* Set everything to floating
* window callback using app regex and set to floating

## Question

1. Am I the only one experience this/something similar and are there any known window callback rules or workarounds that would help?
2. Failing that, is there any way existing or planned to allow certain windows to be completely ignored (rather than forced to floating layout?). Wondering if it would be better for windows like this to be completely left alone rather than handled by aerospace but floating.
3. Any other ideas for addressing this? 

Thanks in advance, really hoping some workaround exists since it seems like others here use IntelliJ IDEs! Happy provide more info if needed 🤞 

(Also let me know if this is, indeed, a dupe - happy to move this to a comment somewhere if it works better)

**Comment by nikitabobko** [comment] 2024-02-20 21:12
Thanks for the detailed report! It's a lot of effort to put so many details in the report

> aerospace debug-windows didn't give me any output relevant to these windows (presumably because they close instantly; too fast for the watcher to pick up).

`debug-windows` didn't give any output because AeroSpace doesn't even treat those IntelliJ popups as windows. I agree that `debug-windows` should be changed to include non-windows in the output

> my problem happens with 'Search Everywhere' and any code completion/intellisense popups.
As soon as I open them, it feels like AeroSpace attempts to 'take control' of the windows, effectively closing them before I can do anything.

Taking into account everything you've described, I have no idea what might be causing this behavior. I happily use IntelliJ IDEA daily and don't have these problems. So it's something with your setup. 

I suggest you start from the beginning: comment everything out in your `aerospace.toml` config, disable hammerspoon/skhd integrations, and see if the problem is still there. Then enable integrations and features one by one to see when the problem manifests itself

**Comment by alexnguyennn** [comment] 2024-02-21 11:43
thanks for the quick response and the hint to divide and conquer to find the culprit, was really helpful to know that it was me and there was at least some possible setup without this happening.
i did as you suggested and seems it was neither `hammerspoon` nor `skhd` but `sketchybar` of all things. I was using [a helper binary](https://github.com/FelixKratz/SketchyBarHelper) attached to a sketchybar item that triggered on `space_windows_change` and `aerospace_workspace_change`, figure `sketchybar` acting on one of those two events is the culprit.

turned it off for now and IDEs are usable again 🎉

speaking of, my `sketchybar` logic was basically trying to recreate the 'stack' layout container labels from i3 ([example](https://github.com/nikitabobko/AeroSpace/assets/12594234/29524a85-cfbe-41f9-8726-589e6bb58d4b)). I used that mode most and always found it really useful to know where apps were relative to the focused one (the accordion padding that exists is ok but not that useful for me personally as a lot of apps look the same on the sides so I end up cycling through blindly anyway).

follow questions: 
1. is some equivalent of this visualisation planned in the future for AeroSpace?
2.  are there plans for making the CLI responsive enough to query and surface the details necessary to emulate 1. possible (e.g. windows in relative order, which one is focused in single list call)? The idea being we could call the CLI from through a separate bar app like `sketchybar` in real time for multiple monitors and (not sure how vertical containers would be representable but at least the horizontal spacing should be straightful)

**Comment by nikitabobko** [comment] 2024-02-21 13:36
> is some equivalent of [this visualisation](https://github.com/nikitabobko/AeroSpace/assets/12594234/29524a85-cfbe-41f9-8726-589e6bb58d4b) planned in the future for AeroSpace?

No, I don't have plans for visualizations like this. However, there are other suggestions in #24 on how to improve the visualization

> are there plans for making the CLI responsive enough to query and surface the details necessary to emulate 1

Please track #104. But honestly, it's not my top priority

**Closed by nikitabobko** 2024-02-21 13:36 UTC
