### ISSUE TITLE
MacOS 15 windows take up space till force quite

### ISSUE THREAD

**Issue by maks112v** [nikitabobko/AeroSpace#601] opened 2024-10-16 22:50 UTC
After upgrading to macOS 15, windows are still taking up space after being closed with the (x) icon or minimized. The only way to get the space back is to force close the application (CMD + Q).

https://github.com/user-attachments/assets/927c6f67-3b26-41e9-86a3-4fc0be718ea5

Aerospace Version: 0.15.2-Beta

**Comment by reastyn** [comment] 2024-10-17 08:29
This is a duplicate of #570

**Closed** 2024-10-17 13:28 UTC
Labels: duplicate
