### ISSUE TITLE
Exclude app from Aerospace management

### ISSUE THREAD

**Issue by Amparose** [nikitabobko/AeroSpace#829] opened 2024-12-07 14:03 UTC
I want some apps to behave as if they are unmanaged by Aerospace: they would show/hide, floated, to my current workspace and not belong to a workspace (e.g. a note app). Alternatively, be able to be assigned to all workspaces (like setting macOS Spaces>All); whichever paradigm is simpler. The outcome should be that **when one of these apps is switched to, they should appear on the current workspace rather than changing workspace**.

This also applies to apps that are modal like [kando-menu/kando: 🥧 The Cross-Platform Pie Menu.](https://github.com/kando-menu/kando?tab=readme-ov-file), which is mostly unusable with Aerospace. Calling a pie menu swaps to workspace 1.

**Comment by nikitabobko** [comment] 2024-12-07 14:04
Duplicate of #2

**Closed by nikitabobko** 2024-12-07 14:04 UTC
Labels: feature-proposal
